/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.prefs.BackingStoreException;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileSystemView;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Billetage extends javax.swing.JFrame {
    PreparedStatement pst = null;
    ResultSet rs = null;
    DBConnection conn;
    DefaultTableModel model = new DefaultTableModel();
    DecimalFormat formatter = new DecimalFormat("#,###.00");
    /**
     * Creates new form Billetage
     */
    public Billetage() {
        initComponents();
        
        try {
            conn = new DBConnection();
        } catch (BackingStoreException ex) {
            Logger.getLogger(InitialDeposits.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            getAllData();
        } catch (ParseException ex) {
            Logger.getLogger(Billetage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        to_transaction_date = new com.toedter.calendar.JDateChooser();
        go = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        from_transaction_date = new com.toedter.calendar.JDateChooser();
        date_choice = new javax.swing.JComboBox<String>();
        transaction_date = new com.toedter.calendar.JDateChooser();
        date_range_label = new javax.swing.JLabel();
        date_label = new javax.swing.JLabel();
        to_label = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_of_transactions = new javax.swing.JTable();
        export = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Transactions Filter"));

        to_transaction_date.setEnabled(false);

        go.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/images/Button-Next-icon.png"))); // NOI18N
        go.setText("GO");
        go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goActionPerformed(evt);
            }
        });

        jLabel3.setText("Date Choice:");

        from_transaction_date.setEnabled(false);

        date_choice.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select One", "Specific Date", "Date Range" }));
        date_choice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date_choiceActionPerformed(evt);
            }
        });

        transaction_date.setEnabled(false);

        date_range_label.setText("Date Range:");

        date_label.setText("Date:");

        to_label.setText("To");
        to_label.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(date_label)
                            .addComponent(date_range_label))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(from_transaction_date, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(to_label)
                                .addGap(16, 16, 16)
                                .addComponent(to_transaction_date, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(transaction_date, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(429, 429, 429)
                        .addComponent(go))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(38, 38, 38)
                        .addComponent(date_choice, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(date_choice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(date_label, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(transaction_date, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(date_range_label)
                    .addComponent(to_transaction_date, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(from_transaction_date, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(to_label))
                .addGap(18, 18, 18)
                .addComponent(go)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        list_of_transactions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Account Number", "Transaction Amount", "5000", "2000", "1000", "500", "100", "50", "20", "10", "5", "1", "Date"
            }
        ));
        jScrollPane1.setViewportView(list_of_transactions);

        jScrollPane2.setViewportView(jScrollPane1);

        export.setText("Export");
        export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 362, Short.MAX_VALUE)
                        .addComponent(export))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(export))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1032, 621));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goActionPerformed
        // TODO add your handling code here:
        String dateChoice = (String) date_choice.getSelectedItem();
        java.sql.Timestamp date = new java.sql.Timestamp(new java.util.Date().getTime());

        if (dateChoice.equalsIgnoreCase("Specific Date")) {
            filterData();
        } else if (dateChoice.equalsIgnoreCase("Date Range")) {
            filterDatabyDate();
        } else {
            JOptionPane.showMessageDialog(null, "Please pick the date choice Filter!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_goActionPerformed

    private void date_choiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date_choiceActionPerformed
        String dateChoice = (String) date_choice.getSelectedItem();
        if (dateChoice.equals("Specific Date")) {
            date_label.setEnabled(true);
            transaction_date.setEnabled(true);
            date_range_label.setEnabled(false);
            from_transaction_date.setEnabled(false);
            to_transaction_date.setEnabled(false);
            to_label.setEnabled(false);
        } else if (dateChoice.equals("Date Range")) {
            date_label.setEnabled(false);
            transaction_date.setEnabled(false);
            date_range_label.setEnabled(true);
            from_transaction_date.setEnabled(true);
            to_transaction_date.setEnabled(true);
            to_label.setEnabled(true);
        }
    }//GEN-LAST:event_date_choiceActionPerformed

    private void exportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportActionPerformed
        // TODO add your handling code here:
        exportTable();
    }//GEN-LAST:event_exportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Billetage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Billetage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Billetage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Billetage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Billetage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> date_choice;
    private javax.swing.JLabel date_label;
    private javax.swing.JLabel date_range_label;
    private javax.swing.JButton export;
    private com.toedter.calendar.JDateChooser from_transaction_date;
    private javax.swing.JButton go;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable list_of_transactions;
    private javax.swing.JLabel to_label;
    private com.toedter.calendar.JDateChooser to_transaction_date;
    private com.toedter.calendar.JDateChooser transaction_date;
    // End of variables declaration//GEN-END:variables
    
    private String formatFloat(String s) {
        float stringToFloat= Float.parseFloat(s);
        return String.valueOf(formatter.format(stringToFloat));
    }
    
    private void getAllData() throws ParseException {
        try {
            DefaultTableModel dtm = (DefaultTableModel) list_of_transactions.getModel();
            dtm.setRowCount(0);
            dtm.setColumnCount(0);
            String sql = null;                  

            sql = "SELECT t.transaction_amount, t.transaction_net_amount, billetage.`account_number`, `5000`, `2000`, `1000`, `500`, `100`, `50`, `20`, `10`, `5`, `1`, t.date_created FROM `billetage` LEFT JOIN transactions t on t.transaction_id = billetage.transaction_id ORDER BY T.date_created DESC";
                pst = conn.connection.prepareStatement(sql);
                rs = pst.executeQuery();
                list_of_transactions.setModel(model);
                model.addColumn("Account Number");
                model.addColumn("Transaction Amount");
                model.addColumn("5000");
                model.addColumn("2000");
                model.addColumn("1000");
                model.addColumn("500");
                model.addColumn("100");
                model.addColumn("50");
                model.addColumn("20");
                model.addColumn("10");
                model.addColumn("5");
                model.addColumn("1");
                model.addColumn("Date");

                while (rs.next()) {
                    model.addRow(new Object[]{rs.getString("Account_Number"), 
                        formatFloat(rs.getString("transaction_amount")),
                        rs.getInt("5000"), 
                        rs.getInt("2000"),
                        rs.getInt("1000"), 
                        rs.getString("500"),
                        rs.getString("100"), 
                        rs.getString("50"),
                        rs.getString("20"),
                        rs.getString("10"),
                        rs.getString("5"),
                        rs.getString("1"),
                        rs.getString("date_created")
                    });
                }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void filterData() {
        if (transaction_date.getDate() == null) {
            JOptionPane.showMessageDialog(null, "The specific date is required for this filter!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            java.util.Date specificDate = transaction_date.getDate();
            java.sql.Date specificDateSql = new java.sql.Date(specificDate.getTime());
            String transactionDate = specificDateSql.toString();

            try {
                DefaultTableModel dtm = (DefaultTableModel) list_of_transactions.getModel();
                dtm.setRowCount(0);
                dtm.setColumnCount(0);
                String sql = null;                  

                sql = "SELECT t.transaction_amount, t.transaction_net_amount, billetage.`account_number`, `5000`, `2000`, `1000`, `500`, `100`, `50`, `20`, `10`, `5`, `1`, t.date_created FROM `billetage` LEFT JOIN transactions t on t.transaction_id = billetage.transaction_id WHERE t.date_created LIKE ? ORDER BY t.date_created DESC";
                    pst = conn.connection.prepareStatement(sql);
                    pst.setString(1, transactionDate);
                    rs = pst.executeQuery();
                    list_of_transactions.setModel(model);
                    model.addColumn("Account Number");
                    model.addColumn("Transaction Amount");
                    model.addColumn("5000");
                    model.addColumn("2000");
                    model.addColumn("1000");
                    model.addColumn("500");
                    model.addColumn("100");
                    model.addColumn("50");
                    model.addColumn("20");
                    model.addColumn("10");
                    model.addColumn("5");
                    model.addColumn("1");
                    model.addColumn("Date");

                    while (rs.next()) {
                        model.addRow(new Object[]{rs.getString("Account_Number"), 
                            formatFloat(rs.getString("transaction_amount")),
                            formatFloat(rs.getString("5000")), 
                            formatFloat(rs.getString("2000")),
                            formatFloat(rs.getString("1000")), 
                            rs.getInt("5000"), 
                            rs.getInt("2000"),
                            rs.getInt("1000"), 
                            rs.getString("500"),
                            rs.getString("100"), 
                            rs.getString("50"),
                            rs.getString("20"),
                            rs.getString("10"),
                            rs.getString("5"),
                            rs.getString("1"),
                            rs.getString("date_created")
                        });
                    }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }

    private void filterDatabyDate() {
        if (from_transaction_date.getDate() == null || to_transaction_date.getDate() == null) {
            JOptionPane.showMessageDialog(null, "The start and end dates are required for this filter!", "Error", JOptionPane.ERROR_MESSAGE);
        }  else {
            java.util.Date fromDate = from_transaction_date.getDate();
            java.util.Date toDate = to_transaction_date.getDate();

            java.sql.Date sqlFromDate = new java.sql.Date(fromDate.getTime());
            java.sql.Date sqlToDate = new java.sql.Date(toDate.getTime());

            try {
                DefaultTableModel dtm = (DefaultTableModel) list_of_transactions.getModel();
                dtm.setRowCount(0);
                dtm.setColumnCount(0);
                String sql = null;                  

                sql = "SELECT t.transaction_amount, t.transaction_net_amount, billetage.`account_number`, `5000`, `2000`, `1000`, `500`, `100`, `50`, `20`, `10`, `5`, `1`, t.date_created FROM `billetage` LEFT JOIN transactions t on t.transaction_id = billetage.transaction_id WHERE t.date_created BETWEEN '" + sqlFromDate.toString() + "%' AND '" + sqlToDate.toString() + "%' ORDER BY t.date_created DESC";
                    pst = conn.connection.prepareStatement(sql);
                    rs = pst.executeQuery();
                    list_of_transactions.setModel(model);
                    model.addColumn("Account Number");
                    model.addColumn("Transaction Amount");
                    model.addColumn("5000");
                    model.addColumn("2000");
                    model.addColumn("1000");
                    model.addColumn("500");
                    model.addColumn("100");
                    model.addColumn("50");
                    model.addColumn("20");
                    model.addColumn("10");
                    model.addColumn("5");
                    model.addColumn("1");
                    model.addColumn("Date");

                    while (rs.next()) {
                        model.addRow(new Object[]{rs.getString("Account_Number"), 
                            formatFloat(rs.getString("transaction_amount")),
                            formatFloat(rs.getString("5000")), 
                            formatFloat(rs.getString("2000")),
                            formatFloat(rs.getString("1000")), 
                            rs.getInt("5000"), 
                            rs.getInt("2000"),
                            rs.getInt("1000"), 
                            rs.getString("500"),
                            rs.getString("100"), 
                            rs.getString("50"),
                            rs.getString("20"),
                            rs.getString("10"),
                            rs.getString("5"),
                            rs.getString("1"),
                            rs.getString("date_created")
                        });
                    }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }
    public void exportTable() {
        try {
         String fileName = "Sacco/";
         String directoryName = FileSystemView.getFileSystemView().getDefaultDirectory().getPath()+"/Documents/".concat(fileName);
         File dir = new File(directoryName);
          if (!dir.exists()) dir.mkdirs();

         ExcelExporter exp = new ExcelExporter();
         exp.exportTable(list_of_transactions, new File(directoryName+"_BILLETAGE.xls"));

         //OPEN FILE
         File tmpDir = new File(directoryName+"_BILLETAGE.xls");
         boolean exists = tmpDir.exists();
           if (exists) {
               Desktop dt = Desktop.getDesktop();
               dt.open(new File(directoryName+"_BILLETAGE.xls"));
           }
       } catch (IOException ex) {
         Logger.getLogger(Transaction.class.getName()).log(Level.SEVERE, null, ex);
       }
    }
}
