/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank;

/**
 *
 * @author chris
 */
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class CreateCollateral extends javax.swing.JFrame {

    /**
     * Creates new form CreateCollateral
     */
    PreparedStatement pst = null;
    ResultSet rs = null;
    DBConnection conn;
    String country = "RW";
    String leBook = "519";

    public CreateCollateral() {
        initComponents();
        conn = new DBConnection();
        lastCollateralID();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        contract_id = new javax.swing.JTextField();
        search_account = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        customer_id = new javax.swing.JTextField();
        jLabel80 = new javax.swing.JLabel();
        save_collateral = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        collateral_last_valuation_date = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        insured = new javax.swing.JComboBox<>();
        rdb_register_number = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        insurance_expiry_date = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        collateral_amount = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        collateral_ownership = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        collateral_discount_amount = new javax.swing.JTextField();
        upi_number = new javax.swing.JTextField();
        registration_number_valuer = new javax.swing.JTextField();
        name_property_valuer = new javax.swing.JTextField();
        ltv_ratio = new javax.swing.JTextField();
        collateral_market_value = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        collateral_type = new javax.swing.JComboBox<>();
        collateral_id = new javax.swing.JFormattedTextField();
        guarantee_issuer = new javax.swing.JTextField();
        collateral_discount_rate = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        collateral_expiry_date = new com.toedter.calendar.JDateChooser();
        cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Search Loan Contract"));

        contract_id.setText("0000000001L");

        search_account.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/images/search-icon.png"))); // NOI18N
        search_account.setText("Search");
        search_account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_accountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contract_id, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(search_account, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contract_id, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_account, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Account Details"));

        customer_id.setEditable(false);

        jLabel80.setText("Customer ID:");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel80)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(customer_id, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel80)
                    .addComponent(customer_id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        save_collateral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/images/save-icon.png"))); // NOI18N
        save_collateral.setText("SAVE");
        save_collateral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_collateralActionPerformed(evt);
            }
        });

        jLabel12.setText("RDB Register Number (*):");

        jLabel1.setText("Collateral Type (*):");

        jLabel17.setText("Collateral ID (*):");

        insured.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Y", "N" }));

        jLabel9.setText("UPI Number (*):");

        jLabel3.setText("Colllateral Amount (*): ");

        jLabel10.setText("Name Property Valuer (*):");

        jLabel11.setText("Registration Number Valuer (*):");

        jLabel4.setText("Collateral Last Valuation Date (*):");

        jLabel16.setText("Guarantee Issuer (*):");

        jLabel2.setText("Collateral Ownership (*):");

        jLabel5.setText("Collateral Expiry Date (*):");

        collateral_ownership.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Y", "N" }));

        jLabel6.setText("Collateral Discount Amount (*):");

        jLabel14.setText("Insured (*):");

        jLabel13.setText("LTV ratio (*):");

        jLabel8.setText("Collateral Market Value (*):");

        jLabel7.setText("Collateral Discount Rate (*): ");

        collateral_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Collateral Type", "CA1", "CA2", "CA3", "CA4", "CA5", "CA6", "FG1", "FG2", "FG3", "FG4", "FG5", "FG6", "FG7", "FG8", "FG9", "FG10", "FG11", "FG12", "FG13", "FG14", "FG15", "FG16", "FG17", "IMA1", "IMA2", "IMA3", "MA1", "MA2", "MA3", "MA4", "MA5", "MA6", "MA7", "MA8", "IIA1", "IIA2", "IIA3", "IIA4", "OA1", "OA2", "OA3", "OA4", "OA5", "OA6" }));

        jLabel15.setText("Insurance Expiry Date (*):");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(collateral_discount_amount)
                                .addComponent(collateral_discount_rate)
                                .addComponent(collateral_market_value)
                                .addComponent(upi_number)
                                .addComponent(name_property_valuer)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13)
                                .addComponent(jLabel14)
                                .addComponent(jLabel15)
                                .addComponent(jLabel16))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(insurance_expiry_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(registration_number_valuer)
                                .addComponent(rdb_register_number)
                                .addComponent(ltv_ratio)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(insured, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(guarantee_issuer, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))
                                    .addGap(54, 54, 54)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(collateral_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(collateral_ownership, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(collateral_id, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel3))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(collateral_expiry_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(collateral_last_valuation_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(collateral_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(4, 4, 4)))
                    .addComponent(jLabel17))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(collateral_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(collateral_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(collateral_ownership, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(collateral_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(collateral_discount_rate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(collateral_last_valuation_date, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(collateral_market_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(collateral_expiry_date, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(upi_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(collateral_discount_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(name_property_valuer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(registration_number_valuer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(rdb_register_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(ltv_ratio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(insured, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15))
                    .addComponent(insurance_expiry_date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(guarantee_issuer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69))
        );

        jScrollPane1.setViewportView(jPanel1);

        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/images/cancel-icon.png"))); // NOI18N
        cancel.setText("CANCEL");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(save_collateral, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(cancel)))
                .addGap(98, 98, 98)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(save_collateral, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    protected void lastCollateralID() {
        try {
            String sql = "SELECT COUNT(*) AS counts FROM (SELECT collaterals.Collateral_ID FROM collaterals) x";
            pst = conn.connection.prepareStatement(sql);
            rs = pst.executeQuery();
            if (rs.next()) {
                //String numberAsString = String.format("%04d", rs.getInt("counts") + 1);
                String collateralIDAsString = String.format("%010d", rs.getInt("counts") + 1);
                collateralIDAsString += "COL";
                collateral_id.setValue(collateralIDAsString);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void searchLoanContract(String contractID) {
        try {
            String sql = "SELECT Contract_ID, Customer_ID from contract_information WHERE Contract_ID =?";
            pst = conn.connection.prepareStatement(sql);
            pst.setString(1, contractID);
            rs = pst.executeQuery();
            if (rs.next()) {
                customer_id.setText(rs.getString("Customer_ID"));
                collateral_id.setText(rs.getString("Contract_ID"));
            } else {
                JOptionPane.showMessageDialog(null, "The Contract ID does not exist!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void saveCollateral() {

        java.util.Date collateralLastValuationDate = collateral_last_valuation_date.getDate();
        java.util.Date collateralExpiryDate = collateral_expiry_date.getDate();
        java.util.Date insuranceExpiryDate = insurance_expiry_date.getDate();

        java.sql.Date sqlCollateralLastValuationDate = new java.sql.Date(collateralLastValuationDate.getTime());
        java.sql.Date sqlCollateralExpiryDate = new java.sql.Date(collateralExpiryDate.getTime());
        java.sql.Date sqlInsuranceExpiryDate = new java.sql.Date(insuranceExpiryDate.getTime());
        try {
            String sql = "insert into collaterals(Country,"
                    + "LE_Book,"
                    + "Contract_ID,"
                    + "Collateral_Id,"
                    + "Customer_Id,"
                    + "Collateral_Type,"
                    + "Collateral_Ownership,"
                    + "Collateral_Amount_LCY,"
                    + "Collateral_Last_Valuation_Date,"
                    + "Collateral_Expiry_Date,"
                    + "Collateral_Discount_Amt_LCY,"
                    + "Collateral_discount_rate,"
                    + "Collateral_market_value,"
                    + "UPI_Number,"
                    + "Name_Property_Valuer,"
                    + "Reg_Number_Valuer,"
                    + "RDB_Reg_number,"
                    + "LTV_ratio,"
                    + "Insured,"
                    + "Insurance_Expiry_date,"
                    + "Gaurantee_Issuer) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

            pst = conn.connection.prepareStatement(sql);
            pst.setString(1, country);
            pst.setString(2, leBook);
            pst.setString(3, contract_id.getText());
            pst.setString(4, collateral_id.getText());
            pst.setString(5, customer_id.getText());
            pst.setString(6, collateral_type.getSelectedItem().toString());
            pst.setString(7, collateral_ownership.getSelectedItem().toString());
            pst.setFloat(8, Float.parseFloat(collateral_amount.getText()));
            pst.setString(9, sqlCollateralLastValuationDate.toString());
            pst.setString(10, sqlCollateralExpiryDate.toString());
            pst.setFloat(11, Float.parseFloat(collateral_discount_amount.getText()));
            pst.setFloat(12, Float.parseFloat(collateral_discount_rate.getText()));
            pst.setFloat(13, Float.parseFloat(collateral_market_value.getText()));

            pst.setString(14, upi_number.getText());
            pst.setString(15, name_property_valuer.getText());
            pst.setString(16, registration_number_valuer.getText());
            pst.setString(17, rdb_register_number.getText());
            pst.setFloat(18, Float.parseFloat(ltv_ratio.getText()));
            pst.setString(19, insured.getSelectedItem().toString());
            pst.setString(20, sqlInsuranceExpiryDate.toString());
            pst.setString(21, guarantee_issuer.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "The contract loan collateral has been Created");
            this.dispose();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void search_accountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_accountActionPerformed
        // TODO add your handling code here:
        if (contract_id.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter the loan contract ID", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            searchLoanContract(contract_id.getText());
        }
    }//GEN-LAST:event_search_accountActionPerformed

    private void save_collateralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_collateralActionPerformed
        // TODO add your handling code here:

        if (collateral_id.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "The collateral ID is required!", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (collateral_type.getSelectedItem().toString().equalsIgnoreCase("Select Collateral Type")) {
            JOptionPane.showMessageDialog(null, "The Collateral Type field is required!", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (collateral_ownership.getSelectedItem().toString().equalsIgnoreCase("Select Y/N")) {
            JOptionPane.showMessageDialog(null, "The Collateral Ownership field is required!", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (collateral_amount.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "The collateral amount field is required!", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (collateral_last_valuation_date.getDate() == null) {
            JOptionPane.showMessageDialog(null, "The collateral last valuation date is required!", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (collateral_expiry_date.getDate() == null) {
            JOptionPane.showMessageDialog(null, "The collateral expiry date is required!", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (collateral_discount_amount.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "The collateral discount amount field is required!", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (collateral_discount_rate.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "The collateral discount rate field is required!", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (collateral_market_value.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "The collateral market value field is required!", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (upi_number.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "The UPI number field is required!", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (name_property_valuer.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "The name property valuer field is required!", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (registration_number_valuer.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "The registration number valuer field is required!", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (rdb_register_number.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "The RDB register number field is required!", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (ltv_ratio.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "The LTV ratio field is required!", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (insured.getSelectedItem().toString().equalsIgnoreCase("Select Y/N")) {
            JOptionPane.showMessageDialog(null, "The Insured field is required!", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (insurance_expiry_date.getDate() == null) {
            JOptionPane.showMessageDialog(null, "The insurance expiry date is required!", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (guarantee_issuer.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "The guarantee isssuer field is required!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            saveCollateral();
        }

    }//GEN-LAST:event_save_collateralActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateCollateral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateCollateral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateCollateral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateCollateral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateCollateral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JTextField collateral_amount;
    private javax.swing.JTextField collateral_discount_amount;
    private javax.swing.JTextField collateral_discount_rate;
    private com.toedter.calendar.JDateChooser collateral_expiry_date;
    private javax.swing.JFormattedTextField collateral_id;
    private com.toedter.calendar.JDateChooser collateral_last_valuation_date;
    private javax.swing.JTextField collateral_market_value;
    private javax.swing.JComboBox<String> collateral_ownership;
    private javax.swing.JComboBox<String> collateral_type;
    private javax.swing.JTextField contract_id;
    private javax.swing.JTextField customer_id;
    private javax.swing.JTextField guarantee_issuer;
    private com.toedter.calendar.JDateChooser insurance_expiry_date;
    private javax.swing.JComboBox<String> insured;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField ltv_ratio;
    private javax.swing.JTextField name_property_valuer;
    private javax.swing.JTextField rdb_register_number;
    private javax.swing.JTextField registration_number_valuer;
    private javax.swing.JButton save_collateral;
    private javax.swing.JButton search_account;
    private javax.swing.JTextField upi_number;
    // End of variables declaration//GEN-END:variables
}
