/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank;

/**
 *
 * @author chris
 */
import com.placeholder.PlaceHolder;
import java.awt.HeadlessException;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.prefs.BackingStoreException;
import java.util.prefs.Preferences;
import javax.swing.JOptionPane;
import java.util.Map;

public class LoanApplication extends javax.swing.JFrame {

    /**
     * Creates new form LoanApplication
     */
    PlaceHolder holder;
    PleaseWait pl = new PleaseWait();
    Preferences prefs = Preferences.userNodeForPackage(Teller_Dashboard.class);
    Helper helper;
    PreparedStatement pst = null;
    ResultSet rs = null;
    DBConnection conn;
    String leBook = "519";
    String country = "RW";
    String currency = "RWF";
    HashMap<String, String> villages;
    HashMap<String, String> economicSectorCodes;
    HashMap<String, String> visionSBUCodes;
    HashMap<String, Integer> loanApplicationTypeCodes;
    HashMap<String, String> loanApplicationStatusCodes;

    public LoanApplication() {
        initComponents();
        helper = new Helper();
        addAllHashMaps();
        try {
            conn = new DBConnection();
        } catch (BackingStoreException ex) {
            Logger.getLogger(LoanApplication.class.getName()).log(Level.SEVERE, null, ex);
        }
        helper = new Helper();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        search_field_choice = new javax.swing.JComboBox<>();
        search_field = new javax.swing.JTextField();
        search_account = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        account_number = new javax.swing.JTextField();
        jLabel80 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        customer_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        customer_gender = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        vision_sbu = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        vision_ouc = new javax.swing.JTextField();
        customer_id = new javax.swing.JFormattedTextField();
        save = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        loan_application_type = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        business_date = new com.toedter.calendar.JDateChooser();
        loan_application_status = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        rejected_reason = new javax.swing.JTextArea();
        applied_amount = new javax.swing.JTextField();
        approved_amount = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        approval_rejection_date = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        loan_utilization_location = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        previous_loans_paid = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        loan_in_other_institutions = new javax.swing.JTextArea();
        economic_sector_code = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        loan_purpose = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        loan_application_date = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        loan_application_id = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Search Account"));

        search_field_choice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Account Number", "ID No" }));

        search_field.setText("310-0002-10");

        search_account.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/images/search-icon.png"))); // NOI18N
        search_account.setText("Search");
        search_account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_accountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(search_field, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(search_account, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(search_field_choice, 0, 148, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(search_field_choice)
                    .addComponent(search_field, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(search_account, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Account Details"));

        account_number.setEditable(false);

        jLabel80.setText("Account Number:");

        jLabel1.setText("Customer Name:");

        customer_name.setEditable(false);

        jLabel2.setText("Gender:");

        customer_gender.setEditable(false);

        jLabel3.setText("Business Segment:");

        vision_sbu.setEditable(false);

        jLabel17.setText("Customer ID:");

        jLabel19.setText("Sacco Branch:");

        customer_id.setEnabled(false);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel80)
                        .addGap(18, 18, 18)
                        .addComponent(account_number, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vision_sbu)
                            .addComponent(vision_ouc, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel17))
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(customer_name, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                    .addComponent(customer_id)))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(customer_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel80)
                    .addComponent(account_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(customer_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(customer_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(customer_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(vision_sbu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(vision_ouc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/images/save-icon.png"))); // NOI18N
        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/images/cancel-icon.png"))); // NOI18N
        cancel.setText("CANCEL");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Application Details"));

        loan_application_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "New Loan Application", "Application to modify existing loan" }));

        jLabel4.setText("Loan Utilization Location (*):");

        jLabel10.setText("Appoval/Rejection Date (*):");

        jLabel9.setText("Loan Application Date (*):");

        loan_application_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Approved", "Rejected" }));
        loan_application_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loan_application_statusActionPerformed(evt);
            }
        });

        rejected_reason.setColumns(20);
        rejected_reason.setRows(5);
        rejected_reason.setEnabled(false);
        jScrollPane2.setViewportView(rejected_reason);

        jLabel11.setText("Previous Loans Paid (*):");

        jLabel5.setText("Loan Purpose (*):");

        loan_utilization_location.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Amajyambere", "Bukinanyana", "Cyimana", "Gataba", "Itetero", "Kabare", "Kamuhire", "Karukamba", "Nyagacyamo", "Rwinzovu", "Urugwiro ", "Uruhongore", "Agasaro", "Gasharu", "Inkingi", "Kanserege", "Kigugu", "Ruganwa", "Umuco", "Umutekano", "Urugero", "Urwibutso", "Amahoro", "Bwiza", "Ihuriro", "Ineza", "Inyange", "Iriba", "Kabagari", "Ubumwe", "Umutako", "Urukundo", "Virunga" }));

        jLabel8.setText("Application Status (*):");

        previous_loans_paid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Y", "N" }));

        loan_in_other_institutions.setColumns(20);
        loan_in_other_institutions.setRows(5);
        jScrollPane3.setViewportView(loan_in_other_institutions);

        economic_sector_code.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Other service activities", "Agriculture, forestry and fishing", "Mining and quarrying", "Manufacturing", "Electricity, gas, steam and air conditioning supply", "Water supply; sewerage, waste management and remediation activities", "Construction", "Wholesale and retail trade; repair of motor vehicles and motorcycles", "Transportation and storage", "Accommodation and food service activities", "Information and communication", "Financial and insurance activities", "Real estate activities", "Professional, scientific and technical activities", "Administrative and support service activities", "Public administration and defence; compulsory social security", "Education", "Human health and social work activities", "Arts, entertainment and recreation", "Activities of households as employers; undifferentiated goods- and services-prod", "Activities of extraterritorial organizations and bodies", "Not Applicable" }));

        jLabel7.setText("Approved Amount (*):");

        jLabel15.setText("Economic Sector Code (*):");

        jLabel12.setText("Rejected Reason:");
        jLabel12.setEnabled(false);

        loan_purpose.setColumns(20);
        loan_purpose.setRows(5);
        jScrollPane1.setViewportView(loan_purpose);

        jLabel6.setText("Applied Amount (*):");

        jLabel13.setText("Loans in Other instituitions:");

        jLabel18.setText("Business Date:");

        jLabel14.setText("Loan Application Type (*):");

        jLabel16.setText("Loan Application ID (*):");

        loan_application_id.setText("000000001L");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(32, 32, 32)
                                .addComponent(previous_loans_paid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(loan_application_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(approval_rejection_date, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(loan_application_status, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(applied_amount)
                                    .addComponent(approved_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(economic_sector_code, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(loan_application_id, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(loan_utilization_location, javax.swing.GroupLayout.Alignment.LEADING, 0, 130, Short.MAX_VALUE)
                                        .addComponent(business_date, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(loan_application_type, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(132, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(65, 65, 65)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 81, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(loan_application_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(economic_sector_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(loan_application_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(loan_application_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(business_date, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(loan_utilization_location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(applied_amount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(approved_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(loan_application_date, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10))
                    .addComponent(approval_rejection_date, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(previous_loans_paid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap())
        );

        jScrollPane4.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(save)
                        .addGap(18, 18, 18)
                        .addComponent(cancel)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(save)
                            .addComponent(cancel))))
                .addContainerGap(133, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static <K, V> K getKey(Map<K, V> map, V value) {
        for (Map.Entry<K, V> entry : map.entrySet()) {
            if (value.equals(entry.getValue())) {
                return entry.getKey();
            }
        }
        return null;
    }

    private void addAllHashMaps() {
        visionSBUCodes = helper.getVisionSBUCodes();
        villages = helper.getVillageCodes();
        economicSectorCodes = helper.getEconomicSectorCodes();
        loanApplicationTypeCodes = helper.getLoanApplicationTypeCodes();
        loanApplicationStatusCodes = helper.getLoanApplicationStastusCodes();
    }

    private boolean doesLoanApplicationID(String loanApplicationID) throws SQLException {
        boolean loanApplicationIDExists = false;
        // TODO Auto-generated method stub
        if (!loanApplicationID.isEmpty()) {
            String sql = "SELECT `Loan_Application_Id` FROM `loan_application_analysis` WHERE Loan_Application_Id = ?";
            pst = conn.connection.prepareStatement(sql);
            pst.setString(1, loanApplicationID);
            rs = pst.executeQuery();
            if (rs.next()) {
                loanApplicationIDExists = true;
            }
        }
        return loanApplicationIDExists;
    }

    private void searchAccount(String searchAccountField, String searchAccountFieldChoice) {
        if (searchAccountFieldChoice.equals("Account Number")) {
            try {
                String sql = "SELECT Customer_Name, "
                        + "Customer_Gender,"
                        + "Customer_ID,"
                        + "Account_Number,"
                        + "Vision_SBU,"
                        + "Forename_1,"
                        + "Vision_OUC from customer_information where Account_Number = ?";
                pst = conn.connection.prepareStatement(sql);
                pst.setString(1, searchAccountField);
                rs = pst.executeQuery();
                if (rs.next()) {
                    account_number.setText(rs.getString("Account_Number"));
                    customer_name.setText(rs.getString("Customer_Name"));
                    customer_gender.setText(rs.getString("Customer_Gender"));
                    vision_sbu.setText(getKey(visionSBUCodes,rs.getString("Vision_SBU")));
                    vision_ouc.setText(rs.getString("Vision_OUC"));
                    customer_id.setText(rs.getString("Customer_ID"));

                } else {
                    JOptionPane.showMessageDialog(null, "Sorry this account does not exist", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(Teller_Dashboard.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private void saveLoanApplication() {
        java.util.Date businessDate = business_date.getDate();
        java.util.Date applicationDate = loan_application_date.getDate();

        java.sql.Date sqlBusinessDate = new java.sql.Date(businessDate.getTime());
        java.sql.Date sqlApplicationDate = new java.sql.Date(applicationDate.getTime());

        try {
            if (doesLoanApplicationID(loan_application_id.getText()) == false) {
                String sql = "insert into loan_application_analysis(Country,"
                        + "LE_Book,"
                        + "Loan_Application_Id,"
                        + "Loan_Application_Type,"
                        + "Business_Date,"
                        + "Customer_ID,"
                        + "Customer_Name,"
                        + "Customer_Gender,"
                        + "Vision_OUC,"
                        + "Loan_Purpose,"
                        + "Loan_Utilization_Location,"
                        + "Vision_SBU,"
                        + "Economic_Sector_Code,"
                        + "Application_Date,"
                        + "Application_Status,"
                        + "Currency,"
                        + "Applied_Amount_LCY,"
                        + "Applied_Amount_FCY,"
                        + "Approved_Amount_LCY,"
                        + "Approved_Amount_FCY,"
                        + "Rejection_Reason,"
                        + "Prev_Loan_Paid,"
                        + "Loan_In_Other_Institutions) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

                pst = conn.connection.prepareStatement(sql);
                pst.setString(1, country);
                pst.setString(2, leBook);
                pst.setString(3, loan_application_id.getText());
                pst.setInt(4, loanApplicationTypeCodes.get((String) loan_application_type.getSelectedItem()));
                pst.setString(5, sqlBusinessDate.toString());
                pst.setString(6, customer_id.getText());
                pst.setString(7, customer_name.getText());
                pst.setString(8, customer_gender.getText());
                pst.setString(9, vision_ouc.getText());
                pst.setString(10, loan_purpose.getText());
                pst.setString(11, villages.get((String) loan_utilization_location.getSelectedItem()));
                pst.setString(12, visionSBUCodes.get(vision_sbu.getText()));
                pst.setString(13, economicSectorCodes.get((String) economic_sector_code.getSelectedItem()));
                pst.setString(14, sqlApplicationDate.toString());
                pst.setString(15, loanApplicationStatusCodes.get((String) loan_application_status.getSelectedItem()));
                pst.setString(16, currency);
                pst.setFloat(17, Float.valueOf((applied_amount.getText()).trim()));
                pst.setFloat(18, Float.valueOf((applied_amount.getText()).trim()));
                pst.setFloat(19, Float.valueOf((approved_amount.getText()).trim()));
                pst.setFloat(20, Float.valueOf((approved_amount.getText()).trim()));
                pst.setString(21, rejected_reason.getText());
                pst.setString(22, (String) previous_loans_paid.getSelectedItem());
                pst.setString(23, loan_in_other_institutions.getText());
                pst.execute();
                JOptionPane.showMessageDialog(null, "Loan Application has been created");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "The loan application with the loan application ID already exists!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (HeadlessException | NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void search_accountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_accountActionPerformed
        // TODO add your handling code here:
        if (search_field.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter account number or customer's ID Number", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            searchAccount(search_field.getText(), search_field_choice.getSelectedItem().toString());
        }
    }//GEN-LAST:event_search_accountActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        if (loan_application_id.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "The Loan Application ID field is required", "Error", JOptionPane.ERROR_MESSAGE);
        }else if (customer_name.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "The Customer Name field is required", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (customer_id.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "The Customer ID Application ID field is required", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (vision_ouc.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "The Sacco Branch ID field is required", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (vision_sbu.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "The Business Segment field is required", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (customer_gender.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "The Customer Gender field is required", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (loan_application_id.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "The Loan Application ID field is required", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (loan_purpose.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "The Loan Purpose field is required", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (economicSectorCodes.get(economic_sector_code.getSelectedItem().toString()) == null) {
            JOptionPane.showMessageDialog(null, "The Economic Sector Code field is required", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (loanApplicationTypeCodes.get(loan_application_type.getSelectedItem().toString()) == null) {
            JOptionPane.showMessageDialog(null, "The Loan Application Type field is required", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (loanApplicationStatusCodes.get(loan_application_status.getSelectedItem().toString()).isEmpty()) {
            JOptionPane.showMessageDialog(null, "The Loan Application Status field is required", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (villages.get(loan_utilization_location.getSelectedItem().toString()) == null) {
            JOptionPane.showMessageDialog(null, "The Loan Utilization field is required", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (applied_amount.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "The Applied Amount field is required", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (approved_amount.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "The Approved Amount field is required", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (loan_purpose.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "The Loan Purpose field is required", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (loan_application_date.getDate() == null) {
            JOptionPane.showMessageDialog(null, "No loan application date specified!", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (approval_rejection_date.getDate() == null) {
            JOptionPane.showMessageDialog(null, "No approval/rejection date specified!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            saveLoanApplication();
        }
    }//GEN-LAST:event_saveActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void loan_application_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loan_application_statusActionPerformed
        // TODO add your handling code here:
        if (loan_application_status.getSelectedItem().toString().equalsIgnoreCase("Rejected")) {
            rejected_reason.setEnabled(true);
        } else {
            rejected_reason.setEnabled(false);
        }
    }//GEN-LAST:event_loan_application_statusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoanApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField account_number;
    private javax.swing.JTextField applied_amount;
    private com.toedter.calendar.JDateChooser approval_rejection_date;
    private javax.swing.JTextField approved_amount;
    private com.toedter.calendar.JDateChooser business_date;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField customer_gender;
    private javax.swing.JFormattedTextField customer_id;
    private javax.swing.JTextField customer_name;
    private javax.swing.JComboBox<String> economic_sector_code;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private com.toedter.calendar.JDateChooser loan_application_date;
    private javax.swing.JFormattedTextField loan_application_id;
    private javax.swing.JComboBox<String> loan_application_status;
    private javax.swing.JComboBox<String> loan_application_type;
    private javax.swing.JTextArea loan_in_other_institutions;
    private javax.swing.JTextArea loan_purpose;
    private javax.swing.JComboBox<String> loan_utilization_location;
    private javax.swing.JComboBox<String> previous_loans_paid;
    private javax.swing.JTextArea rejected_reason;
    private javax.swing.JButton save;
    private javax.swing.JButton search_account;
    private javax.swing.JTextField search_field;
    private javax.swing.JComboBox<String> search_field_choice;
    private javax.swing.JTextField vision_ouc;
    private javax.swing.JTextField vision_sbu;
    // End of variables declaration//GEN-END:variables

}
