/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank;

import com.placeholder.PlaceHolder;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.prefs.BackingStoreException;
import java.util.prefs.Preferences;
import javax.swing.JOptionPane;

/**
 *
 * @author chris
 */
public class LoanOfficerDashboard extends javax.swing.JFrame {

    /**
     * Creates new form LoanOfficerDashboard
     */
    PlaceHolder holder;
    PleaseWait pl = new PleaseWait();
    Preferences prefs = Preferences.userNodeForPackage(Teller_Dashboard.class);
    PreparedStatement pst = null;
    ResultSet rs = null;
    DBConnection conn;
    Helper helper;

    public LoanOfficerDashboard() {
        initComponents();
        conn = new DBConnection();
        helper = new Helper();
        holder = new PlaceHolder(contract_id, "contract ID");
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight();
        this.setSize(xsize, ysize);

        myinfo.setText(prefs.get("title", "") + ": " + prefs.get("firstname", "") + " " + prefs.get("lastname", "").charAt(0) + ".");
        saveupdate.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        new_loan_application = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        new_collateral = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        myinfo = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        exit = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        customer_id = new javax.swing.JTextField();
        jLabel80 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        customer_name = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        contract_id = new javax.swing.JTextField();
        search_account = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        contract_status = new javax.swing.JComboBox<>();
        contract_administrative_fee = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        interest_amount = new javax.swing.JTextField();
        settlement_date = new com.toedter.calendar.JDateChooser();
        apr_rate = new javax.swing.JTextField();
        commissions = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        principal_amount = new javax.swing.JTextField();
        principal_gl = new javax.swing.JTextField();
        start_date = new com.toedter.calendar.JDateChooser();
        insurance_expiry_date = new com.toedter.calendar.JDateChooser();
        govt_schemes_flag = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        interest_rate_cr = new javax.swing.JTextField();
        govt_schemes_description_label = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        currency = new javax.swing.JComboBox<>();
        other_contract_charges = new javax.swing.JTextField();
        deal_sub_type = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        deal_type = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        maturity_date = new com.toedter.calendar.JDateChooser();
        interest_rate_dr = new javax.swing.JTextField();
        interest_rate_method = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        interest_gl = new javax.swing.JTextField();
        insured_flag = new javax.swing.JComboBox<>();
        contract_insurance_charges = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        contract_application_fee = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        govt_schemes_description = new javax.swing.JTextArea();
        delete = new javax.swing.JButton();
        saveupdate = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        view_collaterals = new javax.swing.JButton();
        view_loan_amortization_schedule = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        contract_loans_template = new javax.swing.JButton();
        contract_information_template = new javax.swing.JButton();
        contract_schedules = new javax.swing.JButton();
        loan_application_analysis_template = new javax.swing.JButton();
        contract_collaterals_template = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        jLabel3 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        view_loan_applications = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jToolBar1.setRollover(true);

        new_loan_application.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        new_loan_application.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/images/add-icon.png"))); // NOI18N
        new_loan_application.setText("NEW LOAN APPLICATION");
        new_loan_application.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                new_loan_applicationMouseClicked(evt);
            }
        });
        jToolBar1.add(new_loan_application);
        jToolBar1.add(jSeparator1);

        new_collateral.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        new_collateral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/images/wizard-icon.png"))); // NOI18N
        new_collateral.setText("NEW COLLATERAL");
        new_collateral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                new_collateralMouseClicked(evt);
            }
        });
        jToolBar1.add(new_collateral);
        jToolBar1.add(jSeparator2);

        myinfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        myinfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/images/user-icon.png"))); // NOI18N
        jToolBar1.add(myinfo);
        jToolBar1.add(jSeparator4);

        exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/images/stop-icon.png"))); // NOI18N
        exit.setText("EXIT");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jToolBar1.add(exit);

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Account Details"));

        customer_id.setEditable(false);

        jLabel80.setText("Customer ID:");

        jLabel2.setText("Customer Name:");

        customer_name.setEditable(false);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel80)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(customer_id)
                            .addComponent(customer_name, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel80)
                    .addComponent(customer_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(customer_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Search Loan Contract"));

        contract_id.setText("0000000001L");

        search_account.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/images/search-icon.png"))); // NOI18N
        search_account.setText("Search");
        search_account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_accountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contract_id, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(search_account, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contract_id, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_account, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jScrollPane2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        contract_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "Active", "Pre-Matured", "Matured", "Applied", "Rejected", "Writeoff" }));
        contract_status.setEnabled(false);

        contract_administrative_fee.setEnabled(false);

        jLabel24.setText("Currency (*):");
        jLabel24.setEnabled(false);

        jLabel15.setText("Contract Application Fee (*):");
        jLabel15.setEnabled(false);

        interest_amount.setEnabled(false);

        settlement_date.setEnabled(false);

        apr_rate.setEnabled(false);
        apr_rate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apr_rateActionPerformed(evt);
            }
        });

        commissions.setEnabled(false);

        jLabel14.setText("APR Rate (*):");
        jLabel14.setEnabled(false);

        jLabel23.setText("Insurance Expiry Date (*):");
        jLabel23.setEnabled(false);

        principal_amount.setEnabled(false);

        principal_gl.setEnabled(false);
        principal_gl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                principal_glActionPerformed(evt);
            }
        });

        start_date.setEnabled(false);

        insurance_expiry_date.setEnabled(false);

        govt_schemes_flag.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Y/N", "Y", "N" }));
        govt_schemes_flag.setEnabled(false);
        govt_schemes_flag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                govt_schemes_flagActionPerformed(evt);
            }
        });

        jLabel12.setText("Interest Rate Dr (*):");
        jLabel12.setEnabled(false);

        jLabel9.setText("Deal Sub Type (*):");
        jLabel9.setEnabled(false);

        jLabel21.setText("Insured Flag (*):");
        jLabel21.setEnabled(false);

        jLabel7.setText("Maturity Date (*):");
        jLabel7.setEnabled(false);

        jLabel11.setText("Interest Rate Method (*):");
        jLabel11.setEnabled(false);

        jLabel6.setText("Settlement Date (*):");
        jLabel6.setEnabled(false);

        jLabel29.setText("Contract Status (*):");
        jLabel29.setEnabled(false);

        jLabel25.setText("Principal GL (*):");
        jLabel25.setEnabled(false);

        interest_rate_cr.setEnabled(false);

        govt_schemes_description_label.setText("Govt Schemes Flag (*):");
        govt_schemes_description_label.setEnabled(false);

        jLabel5.setText("Start Date (*):");
        jLabel5.setEnabled(false);

        jLabel8.setText("Deal Type (*):");
        jLabel8.setEnabled(false);

        jLabel28.setText("Interest Amount (*):");
        jLabel28.setEnabled(false);

        currency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RWF" }));
        currency.setEnabled(false);

        other_contract_charges.setEnabled(false);

        deal_sub_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Deal Sub Type" }));
        deal_sub_type.setEnabled(false);

        jLabel16.setText("Contract Administrative Fee (*):");
        jLabel16.setEnabled(false);

        jLabel13.setText("Interest Rate Cr (*):");
        jLabel13.setEnabled(false);

        deal_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Deal Type", "OVRDFT", "SECDEP", "MFIBOW", "MFILON" }));
        deal_type.setEnabled(false);
        deal_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deal_typeActionPerformed(evt);
            }
        });

        jLabel20.setText("Commissions (*):");
        jLabel20.setEnabled(false);

        maturity_date.setEnabled(false);

        interest_rate_dr.setEnabled(false);

        interest_rate_method.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Declining", "Flat ", "Floating", "Not Applicable" }));
        interest_rate_method.setEnabled(false);

        jLabel27.setText("Principal Amount (*):");
        jLabel27.setEnabled(false);

        jLabel22.setText("Contract Insurance Charges (*):");
        jLabel22.setEnabled(false);

        jLabel18.setText("Other Contract Charges (*):");
        jLabel18.setEnabled(false);

        interest_gl.setEnabled(false);

        insured_flag.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Y/N", "Y", "N" }));
        insured_flag.setEnabled(false);

        contract_insurance_charges.setEnabled(false);

        jLabel26.setText("Interest GL (*):");
        jLabel26.setEnabled(false);

        contract_application_fee.setEnabled(false);

        jLabel1.setText("Govt Schemes Description:");
        jLabel1.setEnabled(false);

        govt_schemes_description.setColumns(20);
        govt_schemes_description.setRows(5);
        govt_schemes_description.setEnabled(false);
        jScrollPane1.setViewportView(govt_schemes_description);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel22)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(contract_insurance_charges))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addGap(18, 18, 18)
                            .addComponent(contract_application_fee, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel16)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel18)
                                            .addGap(28, 28, 28)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addGap(88, 88, 88)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel21)
                                    .addGap(89, 89, 89)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(contract_administrative_fee)
                                .addComponent(other_contract_charges)
                                .addComponent(commissions)
                                .addComponent(insured_flag, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(currency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(insurance_expiry_date, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(contract_status, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(interest_amount, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(principal_amount, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(interest_gl, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(principal_gl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(govt_schemes_description_label)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel1))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(interest_rate_method, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(govt_schemes_flag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maturity_date, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(settlement_date, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(start_date, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(apr_rate, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(interest_rate_cr, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(interest_rate_dr, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(deal_type, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deal_sub_type, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(start_date, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addComponent(jLabel6))
                            .addComponent(settlement_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel7))
                    .addComponent(maturity_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(deal_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(deal_sub_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(govt_schemes_description_label)
                    .addComponent(govt_schemes_flag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(interest_rate_method, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(interest_rate_dr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(interest_rate_cr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14))
                    .addComponent(apr_rate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contract_application_fee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(contract_administrative_fee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(other_contract_charges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(commissions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(insured_flag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(contract_insurance_charges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(insurance_expiry_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(currency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(principal_gl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(interest_gl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(principal_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(interest_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(contract_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jScrollPane2.setViewportView(jPanel1);

        delete.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/images/cancel-icon.png"))); // NOI18N
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        saveupdate.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        saveupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/images/save-icon.png"))); // NOI18N
        saveupdate.setText("SAVE");
        saveupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveupdateActionPerformed(evt);
            }
        });

        edit.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/images/edit-icon.png"))); // NOI18N
        edit.setText("EDIT");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        view_collaterals.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        view_collaterals.setText("VIEW COLLATERALS");
        view_collaterals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_collateralsActionPerformed(evt);
            }
        });

        view_loan_amortization_schedule.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        view_loan_amortization_schedule.setText("LOAN AMORTIZATION SCHEDULE");
        view_loan_amortization_schedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_loan_amortization_scheduleActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Loan Templates"));

        contract_loans_template.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        contract_loans_template.setText("Contract Loans");
        contract_loans_template.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contract_loans_templateActionPerformed(evt);
            }
        });

        contract_information_template.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        contract_information_template.setText("Contract Information");
        contract_information_template.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contract_information_templateActionPerformed(evt);
            }
        });

        contract_schedules.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        contract_schedules.setText("Contract Schedules");
        contract_schedules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contract_schedulesActionPerformed(evt);
            }
        });

        loan_application_analysis_template.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        loan_application_analysis_template.setText("Loan Application Analysis");
        loan_application_analysis_template.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loan_application_analysis_templateActionPerformed(evt);
            }
        });

        contract_collaterals_template.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        contract_collaterals_template.setText("Contract Collaterals");
        contract_collaterals_template.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contract_collaterals_templateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contract_loans_template)
                    .addComponent(contract_schedules)
                    .addComponent(loan_application_analysis_template)
                    .addComponent(contract_information_template)
                    .addComponent(contract_collaterals_template))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(contract_collaterals_template)
                .addGap(18, 18, 18)
                .addComponent(contract_information_template)
                .addGap(28, 28, 28)
                .addComponent(contract_loans_template)
                .addGap(18, 18, 18)
                .addComponent(contract_schedules)
                .addGap(18, 18, 18)
                .addComponent(loan_application_analysis_template)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(edit)
                        .addGap(29, 29, 29)
                        .addComponent(saveupdate)
                        .addGap(33, 33, 33)
                        .addComponent(delete))
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(view_collaterals, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(view_loan_amortization_schedule))
                    .addComponent(jScrollPane2))
                .addGap(173, 173, 173)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(298, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edit)
                            .addComponent(saveupdate)
                            .addComponent(delete)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(view_collaterals, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(view_loan_amortization_schedule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jToolBar2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jToolBar2.setRollover(true);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/images/Actions-view-calendar-list-icon.png"))); // NOI18N
        jLabel3.setText("All Loans");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jToolBar2.add(jLabel3);
        jToolBar2.add(jSeparator5);

        view_loan_applications.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        view_loan_applications.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/images/Actions-view-list-details-icon.png"))); // NOI18N
        view_loan_applications.setText("Loan Applications");
        view_loan_applications.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                view_loan_applicationsMouseClicked(evt);
            }
        });
        jToolBar2.add(view_loan_applications);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean validateFields() {
        if (start_date.getDate() == null) {
            JOptionPane.showMessageDialog(null, "The start date is required!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (settlement_date.getDate() == null) {
            JOptionPane.showMessageDialog(null, "The settlement date is required!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (maturity_date.getDate() == null) {
            JOptionPane.showMessageDialog(null, "The maturity date is required!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (deal_type.getSelectedItem().toString().equalsIgnoreCase("Select Deal Type")) {
            JOptionPane.showMessageDialog(null, "The deal type field is required!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (deal_sub_type.getSelectedItem().toString().equalsIgnoreCase("Select Deal Sub Type")) {
            JOptionPane.showMessageDialog(null, "The deal sub type field is required!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (govt_schemes_flag.getSelectedItem().toString().equalsIgnoreCase("Select Y/N")) {
            JOptionPane.showMessageDialog(null, "The deal sub type field is required!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (helper.getInterestRateMethodCode(interest_rate_method.getSelectedItem().toString()) == -1) {
            JOptionPane.showMessageDialog(null, "The interest rate method field is required!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (interest_rate_dr.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "The interest rate debit is required!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (interest_rate_cr.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "The interest rate credit is required!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (apr_rate.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "The APR rate is required!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (contract_application_fee.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "The contract application fee is required!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (contract_administrative_fee.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "The contract administrative fee is required!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (other_contract_charges.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "The other contract charge is required!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (commissions.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "The commission is required!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (contract_insurance_charges.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "The contract insurance charges is required!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (insurance_expiry_date.getDate() == null) {
            JOptionPane.showMessageDialog(null, "The insurance expiry date is required!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (principal_gl.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "The principal GL is required!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (interest_gl.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "The interest GL is required!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (principal_amount.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "The principal amount is required!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (interest_amount.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "The interest amount is required!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (helper.getContractStatusCode(contract_status.getSelectedItem().toString()) == -1) {
            JOptionPane.showMessageDialog(null, "The contract status is required!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else {
            return true;
        }
    }

    private void deleteLoanContract(String contractID) throws SQLException {
        String sql = "DELETE FROM `contract_information` WHERE Contract_ID= ?";
        pst = conn.connection.prepareStatement(sql);
        pst.setString(1, contractID);
        int delete = pst.executeUpdate();
        if (delete > 0) {

            String sql_delete_loan_contract = "DELETE FROM `contract_loans` WHERE Contract_ID=?";
            pst = conn.connection.prepareStatement(sql_delete_loan_contract);
            pst.setString(1, contractID);
            int delete_loan_contract = pst.executeUpdate();
            System.out.println(delete_loan_contract);

            String sql_delete_loan_table = "DELETE FROM `loan_table` WHERE Contract_ID=?";
            pst = conn.connection.prepareStatement(sql_delete_loan_table);
            pst.setString(1, contractID);
            int delete_loan_table = pst.executeUpdate();
            System.out.println(delete_loan_table);

            String sql_delete_loan_amortization = "DELETE FROM `loan_amortization` WHERE Contract_ID=?";
            pst = conn.connection.prepareStatement(sql_delete_loan_amortization);
            pst.setString(1, contractID);
            int delete_loan_amortization = pst.executeUpdate();
            System.out.println(delete_loan_amortization);

            String sql_delete_collateral = "DELETE FROM `collaterals` WHERE Contract_ID=?";
            pst = conn.connection.prepareStatement(sql_delete_collateral);
            pst.setString(1, contractID);
            int delete_collateral = pst.executeUpdate();
            System.out.println(delete_collateral);

            String sql_delete_contract_schedule = "DELETE FROM `contract_schedules` WHERE Contract_ID=?";
            pst = conn.connection.prepareStatement(sql_delete_contract_schedule);
            pst.setString(1, contractID);
            int delete_contract_schedule = pst.executeUpdate();
            System.out.println(delete_contract_schedule);

            String sql_delete_account_information = "DELETE FROM `account_information` WHERE Account_No=?";
            pst = conn.connection.prepareStatement(sql_delete_account_information);
            pst.setString(1, contractID);
            int delete_account_information = pst.executeUpdate();
            System.out.println(delete_account_information);

            String sql_delete_from_loan_epargne_obligatoire = "DELETE FROM `loan_epargne_obligatoire` WHERE Contract_ID=?";
            pst = conn.connection.prepareStatement(sql_delete_from_loan_epargne_obligatoire);
            pst.setString(1, contractID);
            int delete_from_loan_epargne_obligatoire = pst.executeUpdate();
            System.out.println(delete_from_loan_epargne_obligatoire);

            JOptionPane.showMessageDialog(null, "Loan Contract was deleted successfully!", "DELETE ACCOUNT", JOptionPane.CANCEL_OPTION);
        }
    }

    private void updateLoanContractInformation(String loanContractId) {
        if (validateFields()) {
            try {
                java.util.Date startDate = start_date.getDate();
                java.util.Date settlementDate = settlement_date.getDate();
                java.util.Date maturityDate = maturity_date.getDate();
                java.util.Date insuranceExpiryDate = insurance_expiry_date.getDate();

                java.sql.Date sqlStartDate = new java.sql.Date(startDate.getTime());
                java.sql.Date sqlSettlementDate = new java.sql.Date(settlementDate.getTime());
                java.sql.Date sqlMaturityDate = new java.sql.Date(maturityDate.getTime());
                java.sql.Date sqlInsuranceExpiryDate = new java.sql.Date(insuranceExpiryDate.getTime());

                String sql = "UPDATE `contract_information` SET `Start_Date`=?,`Maturity_Date`=?,`Settlement_Date`=?,`Deal_Type`=?,`Deal_Sub_Type`=?,`Govt_Schemes_Flag`=?,`Govt_Schemes_Desc`=?,`Interest_Rate_Method`=?,`Interest_Rate_DR`=?,`Interest_Rate_CR`=?,`APR_Rate`=?,`Contract_Application_Fee`=?,`Contract_Administrative_Fee`=?,`Other_Contract_Charges`=?,`Commissions`=?,`Insured_Flag`=?,`Contract_Insurance_Charges`=?,`Ins_Expiry_Date`=?,`Currency`=?,`Principal_GL`=?,`Interest_GL`=?,`Principal_Amount_FCY`=?,`Principal_Amount_LCY`=?,`Interest_Amount_FCY`=?,`Interest_Amount_LCY`=?,`Contract_Status`=? WHERE Contract_ID = ?";
                pst = conn.connection.prepareStatement(sql);
                pst.setString(1, sqlStartDate.toString());
                pst.setString(2, sqlSettlementDate.toString());
                pst.setString(3, sqlMaturityDate.toString());
                pst.setString(4, deal_type.getSelectedItem().toString());
                pst.setString(5, deal_sub_type.getSelectedItem().toString());
                pst.setString(6, govt_schemes_flag.getSelectedItem().toString());

                pst.setString(7, govt_schemes_description.getText());
                pst.setInt(8, helper.getInterestRateMethodCode(interest_rate_method.getSelectedItem().toString()));
                pst.setFloat(9, Float.parseFloat(interest_rate_dr.getText()));
                pst.setFloat(10, Float.parseFloat(interest_rate_cr.getText()));
                pst.setFloat(11, Float.parseFloat(apr_rate.getText()));
                pst.setFloat(12, Float.parseFloat(contract_application_fee.getText()));
                pst.setFloat(13, Float.parseFloat(contract_administrative_fee.getText()));
                pst.setFloat(14, Float.parseFloat(other_contract_charges.getText()));
                pst.setFloat(15, Float.parseFloat(commissions.getText()));
                pst.setString(16, insured_flag.getSelectedItem().toString());
                pst.setFloat(17, Float.parseFloat(contract_insurance_charges.getText()));
                pst.setString(18, sqlInsuranceExpiryDate.toString());
                pst.setString(19, currency.getSelectedItem().toString());
                pst.setString(20, principal_gl.getText());
                pst.setString(21, interest_gl.getText());
                pst.setFloat(22, Float.parseFloat(principal_amount.getText()));
                pst.setFloat(23, Float.parseFloat(principal_amount.getText()));
                pst.setFloat(24, Float.parseFloat(interest_amount.getText()));
                pst.setFloat(25, Float.parseFloat(interest_amount.getText()));
                pst.setInt(26, helper.getContractStatusCode(contract_status.getSelectedItem().toString()));
                pst.setString(27, loanContractId);
                int update = pst.executeUpdate();
                if (update > 0) {
                    JOptionPane.showMessageDialog(null, "Loan Contract Info has been Updated!");
                    clearFormFields();
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }

    }

    private void clearFormFields() {
        start_date.setEnabled(false);
        //start_date.cleanup();
        settlement_date.setEnabled(false);
        maturity_date.setEnabled(false);
        deal_type.setEnabled(false);
        deal_type.getModel().setSelectedItem("Select Deal Type");
        deal_sub_type.setEnabled(false);
        deal_sub_type.getModel().setSelectedItem("Select Deal Sub Type");
        govt_schemes_flag.setEnabled(false);
        govt_schemes_flag.getModel().setSelectedItem("Select Y/N");
        govt_schemes_description.setEnabled(false);
        govt_schemes_description.setText("");
        interest_rate_method.setEnabled(false);
        govt_schemes_flag.getModel().setSelectedItem("Select Y/N");
        interest_rate_dr.setEnabled(false);
        interest_rate_dr.setText("");
        interest_rate_cr.setEnabled(false);
        interest_rate_cr.setText("");
        apr_rate.setEnabled(false);
        apr_rate.setText("");
        contract_application_fee.setEnabled(false);
        contract_application_fee.setText("");
        contract_administrative_fee.setEnabled(false);
        contract_administrative_fee.setText("");
        other_contract_charges.setEnabled(false);
        other_contract_charges.setText("");
        commissions.setEnabled(false);
        commissions.setText("");
        insured_flag.setEnabled(false);
        insured_flag.getModel().setSelectedItem("Select Y/N");
        contract_insurance_charges.setEnabled(false);
        insurance_expiry_date.setEnabled(false);
        currency.setEnabled(false);
        principal_gl.setEnabled(false);
        principal_gl.setText("");
        interest_gl.setEnabled(false);
        interest_gl.setText("");
        principal_amount.setEnabled(false);
        principal_amount.setText("");
        interest_amount.setEnabled(false);
        interest_amount.setText("");
        contract_status.setEnabled(false);
        contract_status.getModel().setSelectedItem("Select Contract Status");
        saveupdate.setVisible(false);
    }

    private void searchLoanContract(String loanContractId) {

        try {
            String sql = "SELECT Contract_ID, contract_information.Customer_ID, ci.Customer_Name,contract_information.Vision_OUC, contract_information.Vision_SBU, `Start_Date`, `Maturity_Date`, `Settlement_Date`, `Deal_Type`, `Deal_Sub_Type`, `Govt_Schemes_Flag`, `Govt_Schemes_Desc`, `Interest_Rate_Method`, `Interest_Rate_DR`, `Interest_Rate_CR`, `APR_Rate`, `Contract_Application_Fee`, `Contract_Administrative_Fee`, `Other_Contract_Charges`, `Commissions`, `Insured_Flag`, `Contract_Insurance_Charges`, `Ins_Expiry_Date`, `Currency`, `Principal_GL`, `Interest_GL`, `Principal_Amount_FCY`, `Principal_Amount_LCY`, `Interest_Amount_FCY`, `Interest_Amount_LCY`, `Loan_Application_Id`, `Contract_Status` FROM `contract_information` inner JOIN customer_information ci on ci.Customer_ID = contract_information.Customer_ID WHERE Contract_ID = ?";
            pst = conn.connection.prepareStatement(sql);
            pst.setString(1, loanContractId);
            rs = pst.executeQuery();
            if (rs.next()) {
                customer_id.setText(rs.getString("Customer_ID"));
                customer_name.setText(rs.getString("Customer_Name"));
                start_date.setDate(rs.getDate("Start_Date"));
                settlement_date.setDate(rs.getDate("Settlement_Date"));
                maturity_date.setDate(rs.getDate("Maturity_Date"));
                deal_type.getModel().setSelectedItem(rs.getString("Deal_Type"));
                deal_sub_type.getModel().setSelectedItem(rs.getString("Deal_Sub_Type"));
                govt_schemes_flag.getModel().setSelectedItem(rs.getString("Govt_Schemes_Flag"));
                govt_schemes_description.setText(rs.getString("Govt_Schemes_Desc"));
                interest_rate_method.getModel().setSelectedItem(helper.getInterestRateMethod(rs.getString("Interest_Rate_Method")));
                interest_rate_dr.setText(rs.getString("Interest_Rate_DR"));
                interest_rate_cr.setText(rs.getString("Interest_Rate_CR"));
                apr_rate.setText(rs.getString("APR_Rate"));
                contract_application_fee.setText(rs.getString("Contract_Application_Fee"));
                contract_administrative_fee.setText(rs.getString("Contract_Administrative_Fee"));
                other_contract_charges.setText(rs.getString("Other_Contract_Charges"));
                commissions.setText(rs.getString("Commissions"));
                insured_flag.getModel().setSelectedItem(rs.getString("Insured_Flag"));
                contract_insurance_charges.setText(rs.getString("Contract_Insurance_Charges"));
                insurance_expiry_date.setDate(rs.getDate("Ins_Expiry_Date"));
                currency.getModel().setSelectedItem(rs.getString("Currency"));
                principal_gl.setText(rs.getString("Principal_GL"));
                interest_gl.setText(rs.getString("Interest_GL"));
                principal_amount.setText(rs.getString("Principal_Amount_LCY"));
                interest_amount.setText(rs.getString("Interest_Amount_LCY"));
                contract_status.getModel().setSelectedItem(helper.getContractStatus(rs.getString("Contract_Status")));
            } else {
                JOptionPane.showMessageDialog(null, "The Loan Contract ID you entered doesn't exist!", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException ex) {
            Logger.getLogger(LoanOfficerDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    private void new_loan_applicationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_new_loan_applicationMouseClicked
        // TODO add your handling code here:
        new LoanApplication().setVisible(true);
    }//GEN-LAST:event_new_loan_applicationMouseClicked

    private void new_collateralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_new_collateralMouseClicked
        // TODO add your handling code here:
        new CreateCollateral().setVisible(true);
    }//GEN-LAST:event_new_collateralMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            prefs.clear();
        } catch (BackingStoreException ex) {
            Logger.getLogger(Teller_Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_exitMouseClicked

    private void search_accountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_accountActionPerformed
        // TODO add your handling code here:
        if (contract_id.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter the loan contract ID", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            searchLoanContract(contract_id.getText());
        }
    }//GEN-LAST:event_search_accountActionPerformed

    private void apr_rateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apr_rateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apr_rateActionPerformed

    private void principal_glActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_principal_glActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_principal_glActionPerformed

    private void govt_schemes_flagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_govt_schemes_flagActionPerformed
        // TODO add your handling code here:
        if (govt_schemes_flag.getSelectedItem().toString().equalsIgnoreCase("Y")) {
            govt_schemes_description_label.setEnabled(true);
            govt_schemes_description.setEnabled(true);
        } else {
            govt_schemes_description_label.setEnabled(false);
            govt_schemes_description.setEnabled(false);
        }
    }//GEN-LAST:event_govt_schemes_flagActionPerformed

    private void deal_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deal_typeActionPerformed
        // TODO add your handling code here:

        if (deal_type.getSelectedItem().toString().equalsIgnoreCase("OVRDFT")) {
            deal_sub_type.getModel().setSelectedItem("ODLOAN");

        } else if (deal_type.getSelectedItem().toString().equalsIgnoreCase("SECDEP")) {
            deal_sub_type.addItem("SHTDEP");
            deal_sub_type.addItem("MEDDEP");
            deal_sub_type.addItem("LNGDEP");

        } else if (deal_type.getSelectedItem().toString().equalsIgnoreCase("MFIBOW")) {
            deal_sub_type.getModel().setSelectedItem("MFIBOW");
        } else if (deal_type.getSelectedItem().toString().equalsIgnoreCase("MFILON")) {
            deal_sub_type.getModel().setSelectedItem("MFILON");
        } else {
            deal_sub_type.getModel().setSelectedItem("Select Sub Deal Type");
        }
    }//GEN-LAST:event_deal_typeActionPerformed

    private void saveupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveupdateActionPerformed
        // TODO add your handling code here:
        int dialogResult = JOptionPane.showConfirmDialog(null, "Would you like to update this account?");
        if (dialogResult == JOptionPane.YES_OPTION) {
            updateLoanContractInformation(contract_id.getText());
        }
    }//GEN-LAST:event_saveupdateActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        if (!contract_id.getText().isEmpty()) {
            start_date.setEnabled(true);
            settlement_date.setEnabled(true);
            maturity_date.setEnabled(true);
            deal_type.setEnabled(true);
            deal_sub_type.setEnabled(true);
            govt_schemes_flag.setEnabled(true);
            govt_schemes_description.setEnabled(true);
            interest_rate_method.setEnabled(true);
            interest_rate_dr.setEnabled(true);
            interest_rate_cr.setEnabled(true);
            apr_rate.setEnabled(true);
            contract_application_fee.setEnabled(true);
            contract_administrative_fee.setEnabled(true);
            other_contract_charges.setEnabled(true);
            commissions.setEnabled(true);
            insured_flag.setEnabled(true);
            contract_insurance_charges.setEnabled(true);
            insurance_expiry_date.setEnabled(true);
            currency.setEnabled(true);
            principal_gl.setEnabled(true);
            interest_gl.setEnabled(true);
            principal_amount.setEnabled(true);
            interest_amount.setEnabled(true);
            contract_status.setEnabled(true);
            saveupdate.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Please enter account number or customer's ID Number", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_editActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        if (contract_id.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter contract ID", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            int dialogResult = JOptionPane.showConfirmDialog(null, "Would you like to delete this loan contract?");
            if (dialogResult == JOptionPane.YES_OPTION) {
                try {
                    deleteLoanContract(contract_id.getText());
                } catch (SQLException ex) {
                    Logger.getLogger(LoanOfficerDashboard.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void view_collateralsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_collateralsActionPerformed
        // TODO add your handling code here:
        if (contract_id.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter contract ID", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            new ViewCollaterals(contract_id.getText()).setVisible(true);
        }
    }//GEN-LAST:event_view_collateralsActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        new ViewAllLoans().setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void view_loan_amortization_scheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_loan_amortization_scheduleActionPerformed
        // TODO add your handling code here:
        if (contract_id.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter the contract ID", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            new ViewLoanAmortization(contract_id.getText()).setVisible(true);
        }
    }//GEN-LAST:event_view_loan_amortization_scheduleActionPerformed

    private void view_loan_applicationsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_view_loan_applicationsMouseClicked
        // TODO add your handling code here:
        new ViewLoanApplications().setVisible(true);
    }//GEN-LAST:event_view_loan_applicationsMouseClicked

    private void contract_collaterals_templateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contract_collaterals_templateActionPerformed
        // TODO add your handling code here:
        new Template_Contract_Collaterals().setVisible(true);
    }//GEN-LAST:event_contract_collaterals_templateActionPerformed

    private void contract_information_templateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contract_information_templateActionPerformed
        // TODO add your handling code here:
        new Template_Contract_Information().setVisible(true);
    }//GEN-LAST:event_contract_information_templateActionPerformed

    private void contract_loans_templateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contract_loans_templateActionPerformed
        // TODO add your handling code here:
        new Template_Contract_Loans().setVisible(true);
    }//GEN-LAST:event_contract_loans_templateActionPerformed

    private void contract_schedulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contract_schedulesActionPerformed
        // TODO add your handling code here:
        new Template_Contract_Schedules().setVisible(true);
    }//GEN-LAST:event_contract_schedulesActionPerformed

    private void loan_application_analysis_templateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loan_application_analysis_templateActionPerformed
        // TODO add your handling code here:
        new Template_Loan_Application_Analysis().setVisible(true);
    }//GEN-LAST:event_loan_application_analysis_templateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanOfficerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanOfficerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanOfficerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanOfficerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoanOfficerDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apr_rate;
    private javax.swing.JTextField commissions;
    private javax.swing.JTextField contract_administrative_fee;
    private javax.swing.JTextField contract_application_fee;
    private javax.swing.JButton contract_collaterals_template;
    private javax.swing.JTextField contract_id;
    private javax.swing.JButton contract_information_template;
    private javax.swing.JTextField contract_insurance_charges;
    private javax.swing.JButton contract_loans_template;
    private javax.swing.JButton contract_schedules;
    private javax.swing.JComboBox<String> contract_status;
    private javax.swing.JComboBox<String> currency;
    private javax.swing.JTextField customer_id;
    private javax.swing.JTextField customer_name;
    private javax.swing.JComboBox<String> deal_sub_type;
    private javax.swing.JComboBox<String> deal_type;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JLabel exit;
    private javax.swing.JTextArea govt_schemes_description;
    private javax.swing.JLabel govt_schemes_description_label;
    private javax.swing.JComboBox<String> govt_schemes_flag;
    private com.toedter.calendar.JDateChooser insurance_expiry_date;
    private javax.swing.JComboBox<String> insured_flag;
    private javax.swing.JTextField interest_amount;
    private javax.swing.JTextField interest_gl;
    private javax.swing.JTextField interest_rate_cr;
    private javax.swing.JTextField interest_rate_dr;
    private javax.swing.JComboBox<String> interest_rate_method;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JButton loan_application_analysis_template;
    private com.toedter.calendar.JDateChooser maturity_date;
    private javax.swing.JLabel myinfo;
    private javax.swing.JLabel new_collateral;
    private javax.swing.JLabel new_loan_application;
    private javax.swing.JTextField other_contract_charges;
    private javax.swing.JTextField principal_amount;
    private javax.swing.JTextField principal_gl;
    private javax.swing.JButton saveupdate;
    private javax.swing.JButton search_account;
    private com.toedter.calendar.JDateChooser settlement_date;
    private com.toedter.calendar.JDateChooser start_date;
    private javax.swing.JButton view_collaterals;
    private javax.swing.JButton view_loan_amortization_schedule;
    private javax.swing.JLabel view_loan_applications;
    // End of variables declaration//GEN-END:variables
}
