/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank;

import com.placeholder.PlaceHolder;
import javax.swing.*;
import java.util.*;
import java.sql.*;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.prefs.BackingStoreException;
import java.util.prefs.Preferences;

/**
 *
 * @author chris
 */
public class Withdraw extends javax.swing.JFrame {

    /**
     * Creates new form Withdrawal
     */
    PreparedStatement pst = null;
    ResultSet rs = null;
    DBConnection conn;

    public ArrayList<String> listOfcharges = new ArrayList<>();
    PlaceHolder holder;
    Preferences prefs = Preferences.userNodeForPackage(Teller_Dashboard.class);
    String n_employee_key, employee_name;
    String customerId = "";
    String country = "RW";
    String leBook = "A01";
    String currency = "RWF";
    String processOuc = "001"; //branch Id
    String cardNumber = "";
    String merchantId = "";
    String transactionChannel = "PBI";
    float transaction_net_amount;
    int transactionCountDebit;
    int transactionCountCredit;
    private ArrayList<String> listOfSelectedCharges = new ArrayList<>();
    private ArrayList<Float> listOfSelectedAmountCharges = new ArrayList<>();
    float selectedTransactionCharge = 0;
    DecimalFormat formatter = new DecimalFormat("#,###.00");
    float c_balance=0;
    String _accountNumber = "";
    String _transaction_d = "";
    String _employee_name = "";
    String _customerName = "";
    float _previousBalance = 0;
    float _transactionAmount = 0;
    float _transactionCharges = 0;
    float _currentBalance = 0;
    int _transaction_reference = 0;

    public Withdraw() {
        initComponents();
        try {
            conn = new DBConnection();
        } catch (BackingStoreException ex) {
            Logger.getLogger(Withdraw.class.getName()).log(Level.SEVERE, null, ex);
        }
        //listCharges();
        getCountTransactionDebit();
        getCountTransactionCredit();
        holder = new PlaceHolder(debited_amount, "0");
        teller.setText(prefs.get("firstname", "") + " " + prefs.get("lastname", ""));
        n_employee_key = prefs.get("employee_key", "");
        employee_name = prefs.get("firstname", "") + " " + prefs.get("lastname", "");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Withdraw = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        calculate_button = new javax.swing.JButton();
        customer_id_number = new javax.swing.JTextField();
        teller = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        debited_amount = new javax.swing.JTextField();
        current_balance = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        new_balance = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        transaction_type = new javax.swing.JComboBox<String>();
        transaction_description = new javax.swing.JTextField();
        transaction_code = new javax.swing.JComboBox<String>();
        jLabel2 = new javax.swing.JLabel();
        customer_name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        search_account_number = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        transaction_date = new com.toedter.calendar.JDateChooser();
        account_number = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        total_withdrawal_charges = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tenue_de_compte = new javax.swing.JCheckBox();
        fiche = new javax.swing.JCheckBox();
        clearence_form = new javax.swing.JCheckBox();
        salary_commission = new javax.swing.JCheckBox();
        commission_input = new javax.swing.JTextField();
        clearence_form_input = new javax.swing.JTextField();
        fiche_input = new javax.swing.JTextField();
        tenue_de_compte_input = new javax.swing.JTextField();
        historique = new javax.swing.JCheckBox();
        bordereau = new javax.swing.JCheckBox();
        missing_carnet = new javax.swing.JCheckBox();
        carnet = new javax.swing.JCheckBox();
        carnet_input = new javax.swing.JTextField();
        missing_carnet_input = new javax.swing.JTextField();
        bordereau_input = new javax.swing.JTextField();
        historique_input = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        deposited_by = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        amount_in_word = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        fivek = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        twok = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        thusand = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        fivehundred = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        hundred = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        fifty = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        twenty = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        ten = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        five = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        one = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("WITHDRAW");

        Withdraw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/images/web-icon.png"))); // NOI18N
        Withdraw.setText("WITHDRAW");
        Withdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WithdrawActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Withdraw"));

        calculate_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/images/ok1.png"))); // NOI18N
        calculate_button.setText("Total");
        calculate_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculate_buttonActionPerformed(evt);
            }
        });

        customer_id_number.setEditable(false);

        teller.setEditable(false);

        jLabel5.setText("Debited Amount (*):");

        jLabel9.setText("Date (*):");

        current_balance.setEditable(false);
        current_balance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                current_balanceActionPerformed(evt);
            }
        });

        jLabel7.setText("Description:");

        new_balance.setEditable(false);

        jLabel6.setText("Type:");

        transaction_type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Withdraw" }));
        transaction_type.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                transaction_typeItemStateChanged(evt);
            }
        });

        transaction_description.setText("Withdraw");

        transaction_code.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Withdrawal Slips", "Credit - Clearing ACH", "Credit - Clearing RTGS", "Direct Debit", "Standing Orders", "Payment Order - Local" }));
        transaction_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaction_codeActionPerformed(evt);
            }
        });

        jLabel2.setText("Customer Name:");

        customer_name.setEditable(false);

        jLabel1.setText("Account Number:");

        jLabel3.setText("ID Number:");

        jLabel11.setText("Transaction Code (*):");

        search_account_number.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/images/search.gif"))); // NOI18N
        search_account_number.setText("Search");
        search_account_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_account_numberActionPerformed(evt);
            }
        });

        jLabel8.setText("Teller:");

        jLabel4.setText("Current Balance:");

        jLabel12.setText("Charges:");

        jLabel13.setText("Total Charges:");

        total_withdrawal_charges.setEditable(false);
        total_withdrawal_charges.setText("0");

        jLabel14.setText("New Balance:");

        tenue_de_compte.setText("Tenue de Compte");
        tenue_de_compte.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tenue_de_compteStateChanged(evt);
            }
        });
        tenue_de_compte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenue_de_compteActionPerformed(evt);
            }
        });

        fiche.setText("Fiche");
        fiche.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ficheStateChanged(evt);
            }
        });

        clearence_form.setText("Clearence Form");
        clearence_form.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                clearence_formStateChanged(evt);
            }
        });

        salary_commission.setText("Commission");
        salary_commission.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                salary_commissionStateChanged(evt);
            }
        });

        commission_input.setEnabled(false);

        clearence_form_input.setEnabled(false);

        fiche_input.setEnabled(false);

        tenue_de_compte_input.setEnabled(false);

        historique.setText("Historique");
        historique.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                historiqueStateChanged(evt);
            }
        });

        bordereau.setText("Bordereau");
        bordereau.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                bordereauStateChanged(evt);
            }
        });

        missing_carnet.setText("Missing Carnet");
        missing_carnet.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                missing_carnetStateChanged(evt);
            }
        });

        carnet.setText("Carnet");
        carnet.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                carnetStateChanged(evt);
            }
        });

        carnet_input.setEnabled(false);

        missing_carnet_input.setEnabled(false);

        bordereau_input.setEnabled(false);

        historique_input.setEnabled(false);

        jLabel15.setText("Deposited By:");

        jLabel10.setText("Amount In word:");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Money", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("5000:");

        fivek.setText("0");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("2000:");

        twok.setText("0");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("1000:");

        thusand.setText("0");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("500:");

        fivehundred.setText("0");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("100:");

        hundred.setText("0");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("50:");

        fifty.setText("0");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setText("20:");

        twenty.setText("0");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setText("10:");

        ten.setText("0");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setText("5:");

        five.setText("0");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setText("1:");

        one.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(fivek, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(twok, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(thusand, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(32, 32, 32)
                        .addComponent(fifty, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel23)
                        .addGap(32, 32, 32)
                        .addComponent(twenty, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)
                        .addGap(32, 32, 32)
                        .addComponent(ten, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25)))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(fivehundred, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addGap(25, 25, 25)
                        .addComponent(hundred, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(fivek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(twok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(thusand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(fivehundred, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(hundred, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(fifty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(twenty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addGap(197, 197, 197))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(214, 214, 214)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(amount_in_word, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(debited_amount, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(transaction_description, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(transaction_code, javax.swing.GroupLayout.Alignment.LEADING, 0, 160, Short.MAX_VALUE)
                                    .addComponent(transaction_type, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(customer_id_number, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(customer_name, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(account_number, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(current_balance))
                                .addGap(74, 74, 74)
                                .addComponent(search_account_number))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(248, 248, 248))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel13)
                                                .addComponent(jLabel14)
                                                .addComponent(jLabel9))
                                            .addGap(221, 221, 221))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(142, 142, 142))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addGap(51, 51, 51)
                                                .addComponent(deposited_by))
                                            .addComponent(teller, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(transaction_date, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(new_balance, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(total_withdrawal_charges, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(74, 74, 74)
                                        .addComponent(calculate_button, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tenue_de_compte)
                                            .addComponent(fiche)
                                            .addComponent(clearence_form)
                                            .addComponent(salary_commission))
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(commission_input)
                                            .addComponent(clearence_form_input)
                                            .addComponent(fiche_input)
                                            .addComponent(tenue_de_compte_input, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(68, 68, 68)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(historique)
                                            .addComponent(bordereau)
                                            .addComponent(missing_carnet)
                                            .addComponent(carnet))
                                        .addGap(57, 57, 57)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(missing_carnet_input)
                                            .addComponent(bordereau_input)
                                            .addComponent(historique_input)
                                            .addComponent(carnet_input, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 199, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(account_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_account_number))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(customer_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(customer_id_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(transaction_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(transaction_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(transaction_description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(current_balance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(debited_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(amount_in_word, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tenue_de_compte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fiche)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clearence_form)
                        .addGap(6, 6, 6)
                        .addComponent(salary_commission))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(historique)
                            .addComponent(historique_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bordereau)
                            .addComponent(bordereau_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(missing_carnet)
                            .addComponent(missing_carnet_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(carnet)
                            .addComponent(carnet_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tenue_de_compte_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fiche_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearence_form_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(commission_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(total_withdrawal_charges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(new_balance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(calculate_button))
                        .addGap(2, 2, 2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(transaction_date, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(teller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deposited_by, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1028, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Withdraw)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(Withdraw)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private ArrayList<String> getArrayListOfSelectedCharges() {

        ArrayList<String> selectedCharges = new ArrayList<>();

        if (tenue_de_compte.isSelected() && !tenue_de_compte_input.getText().isEmpty()) {
            selectedCharges.add(tenue_de_compte.getText());
        }
        if (historique.isSelected() && !historique_input.getText().isEmpty()) {
            selectedCharges.add(historique.getText());
        }
        if (carnet.isSelected() && !carnet_input.getText().isEmpty()) {
            selectedCharges.add(carnet.getText());
        }
        if (fiche.isSelected() && !fiche_input.getText().isEmpty()) {
            selectedCharges.add(fiche.getText());
        }
        if (bordereau.isSelected() && !bordereau_input.getText().isEmpty()) {
            selectedCharges.add(bordereau.getText());
        }
        if (salary_commission.isSelected() && !commission_input.getText().isEmpty()) {
            selectedCharges.add(salary_commission.getText());
        }
        if (clearence_form.isSelected() && !clearence_form_input.getText().isEmpty()) {
            selectedCharges.add(clearence_form.getText());
        }
        if (missing_carnet.isSelected() && !missing_carnet_input.getText().isEmpty()) {
            selectedCharges.add(missing_carnet.getText());
        }

        return selectedCharges;
    }
    
    private ArrayList<Float> getArrayListOfSelectedAmountCharges() {

        ArrayList<Float> selectedAmountCharges = new ArrayList<>();

        if (tenue_de_compte.isSelected() && !tenue_de_compte_input.getText().isEmpty()) {
            selectedAmountCharges.add(Float.parseFloat(tenue_de_compte_input.getText()));
        }
        if (historique.isSelected() && !historique_input.getText().isEmpty()) {
            selectedAmountCharges.add(Float.parseFloat(historique_input.getText()));
        }
        if (carnet.isSelected() && !carnet_input.getText().isEmpty()) {
            selectedAmountCharges.add(Float.parseFloat(carnet_input.getText()));
        }
        if (fiche.isSelected() && !fiche_input.getText().isEmpty()) {
            selectedAmountCharges.add(Float.parseFloat(fiche_input.getText()));
        }
        if (bordereau.isSelected() && !bordereau_input.getText().isEmpty()) {
            selectedAmountCharges.add(Float.parseFloat(bordereau_input.getText()));
        }
        if (salary_commission.isSelected() && !commission_input.getText().isEmpty()) {
            selectedAmountCharges.add(Float.parseFloat(commission_input.getText()));
        }
        if (clearence_form.isSelected() && !clearence_form_input.getText().isEmpty()) {
            selectedAmountCharges.add(Float.parseFloat(clearence_form_input.getText()));
        }
        if (missing_carnet.isSelected() && !missing_carnet_input.getText().isEmpty()) {
            selectedAmountCharges.add(Float.parseFloat(missing_carnet_input.getText()));
        }

        return selectedAmountCharges;
    }

    private void getCountTransactionCredit() {
        try {
            String sql = "SELECT Trans_Count_CR FROM financial_transaction WHERE transaction_type = 'Deposit' ORDER BY id DESC LIMIT 1";
            pst = conn.connection.prepareStatement(sql);
            rs = pst.executeQuery();
            if (rs.next()) {
                transactionCountCredit = rs.getInt("Trans_Count_CR");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void getCountTransactionDebit() {
        try {
            String sql = "SELECT COUNT(*) AS counts FROM (SELECT transactions.transaction_id FROM transactions WHERE transaction_type = 'Withdraw') x";
            pst = conn.connection.prepareStatement(sql);
            rs = pst.executeQuery();
            if (rs.next()) {
                transactionCountDebit = rs.getInt("counts") + 1;
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public static Calendar toCalendar(java.util.Date date) {
        Calendar cal = Calendar.getInstance();
        cal.setTime(date);
        return cal;
    }

    public int getMonthYear(Calendar date) {
        int month = date.get(Calendar.MONTH) + 1;
        int year = date.get(Calendar.YEAR);

        //if ()
        int monthYear = Integer.parseInt(month + "" + year);
        return monthYear;
    }

    private String getChargeAmount(String chargename) {
        String amount = "";
        String sql = "Select amount from charges WHERE charge_name='" + chargename + "'";
        try {
            pst = conn.connection.prepareStatement(sql);
            rs = pst.executeQuery();
            if (rs.next()) {
                amount = rs.getString("amount");
                total_withdrawal_charges.setText(amount);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                rs.close();
                pst.close();
            } catch (SQLException e) {

            }
        }
        return amount;
    }

    public String getChargeCalculation(String chargename) {
        String chargeCalculation = "";
        String sql = "Select charge_calculation from charges WHERE charge_name='" + chargename + "'";
        try {
            pst = conn.connection.prepareStatement(sql);
            rs = pst.executeQuery();
            if (rs.next()) {
                chargeCalculation = rs.getString("charge_calculation");
                //totalCharges.setText(amount);  
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                rs.close();
                pst.close();
            } catch (SQLException e) {

            }
        }
        return chargeCalculation;
    }

    private void searchAccount(String accountNumber) {
        try {
            String sql = "SELECT Account_Number,Customer_ID, Customer_Name, National_ID_Number from customer_information where Account_Number = ?";
            pst = conn.connection.prepareStatement(sql);
            pst.setString(1, accountNumber);
            rs = pst.executeQuery();
            if (rs.next()) {
                customerId = rs.getString("Customer_ID");
                customer_name.setText(rs.getString("Customer_Name"));
                customer_id_number.setText(rs.getString("National_ID_Number"));
                //current_balance.setText(getCurrrentBalance(rs.getString("account_number")).toString());
                current_balance.setText(String.valueOf(getCurrrentBalance(rs.getString("Account_Number"))));
                c_balance=getCurrrentBalance(rs.getString("Account_Number"));
            } else {
                JOptionPane.showMessageDialog(null, "Sorry this account does not exist!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    

    private float getCurrrentBalance(String accountNumber) {
        String sql = "SELECT * FROM balance WHERE Account_Number = ?";
        float balance = 0;
        try {
            pst = conn.connection.prepareStatement(sql);
            pst.setString(1, accountNumber);
            rs = pst.executeQuery();
            if (rs.next()) {
                balance = rs.getFloat("current_balance");
            }
        } catch (SQLException ex) {
            // TODO Auto-generated catch block
            JOptionPane.showMessageDialog(null, ex);
        }
        return balance;
    }
    
    private int getTransaction_ref(String accountNumber) {
        String sql = "SELECT `transaction_id` FROM `transactions` WHERE transactions.Account_Number =?  ORDER BY transaction_id desc  LIMIT 1";
        int transaction_id = 0;
        try {
            pst = conn.connection.prepareStatement(sql);
            pst.setString(1, accountNumber);
            rs = pst.executeQuery();
            if (rs.next()) {
                transaction_id = rs.getInt("transaction_id");
            }
        } catch (SQLException ex) {
            // TODO Auto-generated catch block
            JOptionPane.showMessageDialog(null, ex);
        }
        return transaction_id;
    }

    private String getTransactionCode(String transaction) {

        switch (transaction) {
            case "Credit - Clearing ACH":
                return "TC00005";
            case "Credit - Clearing RTGS":
                return "TC00006";
            case "Direct Debit":
                return "TC00007";
            case "Standing Orders":
                return "TC00008";
            case "Withdrawal Slips":
                return "TC00009";
            case "Deposite Slips":
                return "TC00010";
            case "Payment Order - Local":
                return "TC00056";
            default:
                return "";
        }
    }

    private void updateTransactionDate(String accountNumber, String transactionDate) {
        try {
            String sql = "update account_information set Last_Transaction_Date	='" + transactionDate + "' where Customer_ID='" + customerId + "'";
            pst = conn.connection.prepareStatement(sql);
            pst.execute();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void updateFinancialTransactionsTable(String country, String leBook, int yearMonth,
            String accountNumber, String processOuc, String cardNumber, String merchantId,
            String transactionChannel, String transactionCode, String currency,
            int transactionCountDebit, int transactionCountCredit, float transactionAmountDebit,
            float transactionAmountCredit, String transactionDate, String transactionType) {

        try {
            String sql = "INSERT INTO `financial_transaction`(`Country`, "
                    + "`LE_Book`, "
                    + "`Year_Month`, "
                    + "`Account_Number`, "
                    + "`Process_Ouc`, "
                    + "`Card_No`, "
                    + "`Merchant_Id`, "
                    + "`Transaction_Channel`, "
                    + "`Transaction_Code`, "
                    + "`Currency`, "
                    + "`Trans_Count_DR`, "
                    + "`Trans_Count_CR`, "
                    + "`Trans_Amount_DR_FCY`, "
                    + "`Trans_Amount_CR_FCY`, "
                    + "`Trans_Amount_DR_LCY`, "
                    + "`Trans_Amount_CR_LCY`, "
                    + "`transaction_type`, "
                    + "`transaction_date`) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            pst = conn.connection.prepareStatement(sql);
            pst.setString(1, country);
            pst.setString(2, leBook);
            pst.setInt(3, yearMonth);
            pst.setString(4, accountNumber);
            pst.setString(5, processOuc);
            pst.setString(6, cardNumber);
            pst.setString(7, merchantId);
            pst.setString(8, transactionChannel);
            pst.setString(9, transactionCode);
            pst.setString(10, currency);
            pst.setInt(11, transactionCountDebit);
            pst.setInt(12, transactionCountCredit);
            pst.setFloat(13, transactionAmountDebit);
            pst.setFloat(14, transactionAmountCredit);
            pst.setFloat(15, transactionAmountDebit);
            pst.setFloat(16, transactionAmountCredit);
            pst.setString(17, transactionType);
            pst.setString(18, transactionDate);
            pst.execute();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private boolean doesAccountExist(String acc) throws SQLException {
        boolean accountExists = false;
        // TODO Auto-generated method stub
        if (!acc.isEmpty()) {
            String sql = "SELECT `Account_Number` FROM `customer_information` WHERE Account_Number = ?";
            pst = conn.connection.prepareStatement(sql);
            pst.setString(1, acc);
            rs = pst.executeQuery();
            if (rs.next()) {
                accountExists = true;
            }
        }
        return accountExists;
    }

    private boolean validateWithdrawFields() {

        if (current_balance.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "The current balance field is required!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (debited_amount.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "The debited amount field is required!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else {
            return true;
        }
    }

    private boolean recordWithdrawal(float transactionAmount, float transactionCharge, float transaction_net_amount,
            float previousBalance, float currentBalance, String transactionDate, String transactionType,
            String transactionDescription, String accountNumber, String employeeKey) throws SQLException, ParseException {
        boolean message;

        String sql = "insert into transactions(transaction_amount,"
                + "transaction_charge,"
                + "transaction_net_amount,"
                + "previous_balance,"
                + "current_balance,"
                + "transaction_date,"
                + "transaction_type,"
                + "transaction_description,"
                + "Account_Number,"
                + "requestee, "
                + "employee_key) values (?,?,?,?,?,?,?,?,?,?,?)";
        pst = conn.connection.prepareStatement(sql);
        pst.setFloat(1, transactionAmount);
        pst.setFloat(2, transactionCharge);
        pst.setFloat(3, transaction_net_amount);
        pst.setFloat(4, previousBalance);
        pst.setFloat(5, currentBalance);
        pst.setString(6, transactionDate);
        pst.setString(7, transactionType);
        pst.setString(8, transactionDescription);
        pst.setString(9, accountNumber);
        pst.setString(10, accountNumber);
        pst.setString(11, employeeKey);
        int saved = pst.executeUpdate();

        if (saved > 0) {
            searchAccount(accountNumber);
            this.debited_amount.setText("");
            return message = true;
        }
        return message = false;

    }

    private void updateProductsTable(String chargeDescription, float transactionCharge, String transactionDate, String accountNumber) {
        try {
            String sql = "insert into product (description,amount,product_date,Account_Number) values(?,?,?,?)";
            pst = conn.connection.prepareStatement(sql);
            pst.setString(1, chargeDescription);
            pst.setFloat(2, transactionCharge);
            pst.setString(3, transactionDate);
            pst.setString(4, accountNumber);
            pst.execute();
            //JOptionPane.showMessageDialog(null, "Successfully Withdraws");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private String getTransaction_date(String accountNumber) {
        String sql = "SELECT `date_created` FROM `transactions` WHERE transactions.Account_Number =?  ORDER BY transaction_id desc  LIMIT 1";
        String transaction_date = "";
        try {
            pst = conn.connection.prepareStatement(sql);
            pst.setString(1, accountNumber);
            rs = pst.executeQuery();
            if (rs.next()) {
                transaction_date = rs.getString("date_created");
            }
        } catch (SQLException ex) {
            // TODO Auto-generated catch block
            JOptionPane.showMessageDialog(null, ex);
        }
        return transaction_date;
    }

    private void save_withdrawal(String accountNumber, String customerName, float previousBalance,
            float currentBalance, float transactionAmount, float transactionCharges, float transaction_net_amount, String transactionDate,
            String transactionType, String transactionDescription, String teller, float transactionAmountCredit,
            String transactionCode, int transactionCountDebit, float transactionAmountDebit, int yearMonth,
            String chargeDescription) throws SQLException {

        if (doesAccountExist(accountNumber)) {
            if (transactionAmount < 0) {
                JOptionPane.showMessageDialog(null, "Please specify amount to withdraw", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (previousBalance > transactionAmount) {

                String sql = "UPDATE `balance` SET `current_balance` = ?, date_changed  = ? WHERE Account_Number = ?";
                pst = conn.connection.prepareStatement(sql);
                pst.setFloat(1, Float.parseFloat(new_balance.getText()));
                pst.setString(2, transactionDate);
                pst.setString(3, accountNumber);

                int updated = pst.executeUpdate();
                if (updated > 0) {
                    try {
                        if (recordWithdrawal(transactionAmount, transactionCharges, transaction_net_amount, previousBalance, currentBalance,
                                transactionDate, transactionType, transactionDescription, accountNumber, n_employee_key)) {
                            JOptionPane.showMessageDialog(null, "Withdraw successfull!");
                            updateFinancialTransactionsTable(country, leBook, yearMonth, accountNumber, processOuc,
                                    cardNumber, merchantId, transactionChannel, transactionCode, currency,
                                    transactionCountDebit, transactionCountCredit, transactionAmountDebit,
                                    transactionAmountCredit, transactionDate, transactionType);
                            for (int i = 0; i < listOfSelectedCharges.size(); i++) {

                                selectedTransactionCharge = listOfSelectedAmountCharges.get(i);
                                chargeDescription = listOfSelectedCharges.get(i);
                                
                                updateProductsTable(chargeDescription, selectedTransactionCharge, transactionDate, accountNumber);
                            }
                            updateTransactionDate(accountNumber, transactionDate);
                            
                            int transaction_reference =getTransaction_ref(accountNumber);
                            String transaction_d = getTransaction_date(accountNumber);
                            String amounti_w= amount_in_word.getText();
                            //save billatage
                            saveBillatage(transaction_reference, accountNumber);
                            
                            new ReceiptPrinatable("Deposit", accountNumber, customerName, previousBalance, transactionAmount, amounti_w, transactionCharges,
                                    currentBalance, transaction_d, employee_name, transaction_reference, transaction_description.getText(), deposited_by.getText()
                                    , Integer.parseInt(fivek.getText()),
                                    Integer.parseInt(twok.getText()),
                                    Integer.parseInt(thusand.getText()),
                                    Integer.parseInt(fivehundred.getText()),
                                    Integer.parseInt(hundred.getText()),
                                    Integer.parseInt(fifty.getText()),
                                    Integer.parseInt(twenty.getText()),
                                    Integer.parseInt(ten.getText()),
                                    Integer.parseInt(five.getText()),
                                    Integer.parseInt(one.getText())
                            );
                        }
                    } catch (ParseException ex) {
                        Logger.getLogger(Deposit.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Insufficient funds!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "This account number (" + accountNumber + ") does not exist.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void search_account_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_account_numberActionPerformed
        // TODO add your handling code here:
        if (account_number.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter account number", "Error", JOptionPane.ERROR_MESSAGE);
            //save_person.setEnabled(false);
        } else {
            searchAccount(account_number.getText());
        }
    }//GEN-LAST:event_search_account_numberActionPerformed

    private void WithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WithdrawActionPerformed
        // TODO add your handling code here:

        if (account_number.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "The account number field is required", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (transaction_code.getSelectedItem().toString().equalsIgnoreCase("Select One")) {
            JOptionPane.showMessageDialog(null, "The transaction code field required", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (new_balance.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "The new balance field is required", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            String transactionCode = getTransactionCode((String) transaction_code.getSelectedItem());
            //transactionCountCredit++;

            String accountNumber = account_number.getText();
            String customerName = customer_name.getText();
            float previousBalance = Float.parseFloat(current_balance.getText());
            float transactionAmount = Float.parseFloat(debited_amount.getText());
            float transactionCharges = Float.parseFloat(total_withdrawal_charges.getText());
            float currentBalance = Float.parseFloat(new_balance.getText());
            String chargeDescription = "";
            java.util.Date tdate = transaction_date.getDate();
            java.sql.Date transactionDate = new java.sql.Date(tdate.getTime());
            Calendar date = toCalendar(tdate);

            int yearMonth = getMonthYear(date);

            float transactionAmountDebit = transactionAmount;
            float transactionAmountCredit = 0;
            String transactionType = (String) transaction_type.getSelectedItem();
            String transactionDescription = transaction_description.getText();

            transaction_net_amount = transactionAmount + transactionCharges;
            listOfSelectedCharges = getArrayListOfSelectedCharges();
            listOfSelectedAmountCharges = getArrayListOfSelectedAmountCharges();

            try {
                save_withdrawal(accountNumber, customerName, previousBalance, currentBalance, transactionAmount, transactionCharges,
                        transaction_net_amount, transactionDate.toString(), transactionType, transactionDescription, teller.getText(),
                        transactionAmountCredit, transactionCode, transactionCountDebit,
                        transactionAmountDebit, yearMonth, chargeDescription);
                
                //decrease teller balance
                new AppClass().modifyTellerBalance(conn, pst, rs, n_employee_key, transactionAmount, transactionDate.toString(), "Withdraw");
                
            } catch (SQLException ex) {
                Logger.getLogger(Deposit.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_WithdrawActionPerformed

    private void calculate_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculate_buttonActionPerformed
        // TODO add your handling code here:
        if (validateWithdrawFields()) {
            try {
                float allCharges = 0;
                float newBalance = 0;
                float oldBalance = Float.parseFloat(current_balance.getText());
                float debitedAmount = Float.parseFloat(debited_amount.getText());

                if (tenue_de_compte.isSelected() && !tenue_de_compte_input.getText().isEmpty()) {
                    allCharges += Float.parseFloat(tenue_de_compte_input.getText());
                }
                if (historique.isSelected() && !historique_input.getText().isEmpty()) {
                    allCharges += Float.parseFloat(historique_input.getText());
                }
                if (carnet.isSelected() && !carnet_input.getText().isEmpty()) {
                    allCharges += Float.parseFloat(carnet_input.getText());
                }
                if (fiche.isSelected() && !fiche_input.getText().isEmpty()) {
                    allCharges += Float.parseFloat(fiche_input.getText());
                }
                if (bordereau.isSelected() && !bordereau_input.getText().isEmpty()) {
                    allCharges += Float.parseFloat(bordereau_input.getText());
                }
                if (salary_commission.isSelected() && !commission_input.getText().isEmpty()) {
                    allCharges += Float.parseFloat(commission_input.getText());
                }
                if (clearence_form.isSelected() && !clearence_form_input.getText().isEmpty()) {
                    allCharges += Float.parseFloat(clearence_form_input.getText());
                }
                if (missing_carnet.isSelected() && !missing_carnet_input.getText().isEmpty()) {
                    allCharges += Float.parseFloat(missing_carnet_input.getText());
                }
                else {
                    allCharges += 0;
                }

                if (oldBalance - debitedAmount < allCharges) {
                    JOptionPane.showMessageDialog(null, "Insufficient funds!", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    System.out.println(allCharges);
                    total_withdrawal_charges.setText(String.valueOf(allCharges));
                    newBalance = oldBalance - debitedAmount - allCharges;
                    new_balance.setText(String.valueOf(newBalance));
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_calculate_buttonActionPerformed

    private void transaction_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaction_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transaction_codeActionPerformed

    private void current_balanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_current_balanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_current_balanceActionPerformed

    private void transaction_typeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_transaction_typeItemStateChanged
        // TODO add your handling code here:
        if(transaction_type.getSelectedItem().toString().equalsIgnoreCase("Closing Balance")){
            current_balance.setText("0.0");
            current_balance.setEditable(true);
        }else{
            current_balance.setEditable(false);
            current_balance.setText(c_balance+"");
        }
    }//GEN-LAST:event_transaction_typeItemStateChanged

    private void tenue_de_compteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tenue_de_compteStateChanged
        // TODO add your handling code here:

        if (tenue_de_compte.isSelected()) {
            tenue_de_compte_input.setEnabled(true);
        }else{
            tenue_de_compte_input.setEnabled(false);
            tenue_de_compte_input.setText("");
        }
    }//GEN-LAST:event_tenue_de_compteStateChanged

    private void ficheStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ficheStateChanged
        // TODO add your handling code here:

        if (fiche.isSelected()) {
            fiche_input.setEnabled(true);
        }else{
            fiche_input.setEnabled(false);
            fiche_input.setText("");
        }
    }//GEN-LAST:event_ficheStateChanged

    private void clearence_formStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_clearence_formStateChanged
        // TODO add your handling code here:
        if (clearence_form.isSelected()) {
            clearence_form_input.setEnabled(true);
        }else{
            clearence_form_input.setEnabled(false);
            clearence_form_input.setText("");
        }
    }//GEN-LAST:event_clearence_formStateChanged

    private void salary_commissionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_salary_commissionStateChanged
        // TODO add your handling code here:
        if (salary_commission.isSelected()) {
            commission_input.setEnabled(true);
        }else{
            commission_input.setEnabled(false);
            commission_input.setText("");
        }
    }//GEN-LAST:event_salary_commissionStateChanged

    private void historiqueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_historiqueStateChanged
        // TODO add your handling code here:
        if (historique.isSelected()) {
            historique_input.setEnabled(true);
        }else{
            historique_input.setEnabled(false);
            historique_input.setText("");
        }
    }//GEN-LAST:event_historiqueStateChanged

    private void bordereauStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_bordereauStateChanged
        // TODO add your handling code here:
        if (bordereau.isSelected()) {
            bordereau_input.setEnabled(true);
        }else{
            bordereau_input.setEnabled(false);
            bordereau_input.setText("");
        }
    }//GEN-LAST:event_bordereauStateChanged

    private void missing_carnetStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_missing_carnetStateChanged
        // TODO add your handling code here:
        if (missing_carnet.isSelected()) {
            missing_carnet_input.setEnabled(true);
        }else{
            missing_carnet_input.setEnabled(false);
            missing_carnet_input.setText("");
        }
    }//GEN-LAST:event_missing_carnetStateChanged

    private void carnetStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_carnetStateChanged
        // TODO add your handling code here:
        if (carnet.isSelected()) {
            carnet_input.setEnabled(true);
        }else{
            carnet_input.setEnabled(false);
            carnet_input.setText("");
        }
    }//GEN-LAST:event_carnetStateChanged

    private void tenue_de_compteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenue_de_compteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenue_de_compteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Withdraw().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Withdraw;
    private javax.swing.JTextField account_number;
    private javax.swing.JTextField amount_in_word;
    private javax.swing.JCheckBox bordereau;
    private javax.swing.JTextField bordereau_input;
    private javax.swing.JButton calculate_button;
    private javax.swing.JCheckBox carnet;
    private javax.swing.JTextField carnet_input;
    private javax.swing.JCheckBox clearence_form;
    private javax.swing.JTextField clearence_form_input;
    private javax.swing.JTextField commission_input;
    private javax.swing.JTextField current_balance;
    private javax.swing.JTextField customer_id_number;
    private javax.swing.JTextField customer_name;
    private javax.swing.JTextField debited_amount;
    private javax.swing.JTextField deposited_by;
    private javax.swing.JCheckBox fiche;
    private javax.swing.JTextField fiche_input;
    private javax.swing.JTextField fifty;
    private javax.swing.JTextField five;
    private javax.swing.JTextField fivehundred;
    private javax.swing.JTextField fivek;
    private javax.swing.JCheckBox historique;
    private javax.swing.JTextField historique_input;
    private javax.swing.JTextField hundred;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox missing_carnet;
    private javax.swing.JTextField missing_carnet_input;
    private javax.swing.JTextField new_balance;
    private javax.swing.JTextField one;
    private javax.swing.JCheckBox salary_commission;
    private javax.swing.JButton search_account_number;
    private javax.swing.JTextField teller;
    private javax.swing.JTextField ten;
    private javax.swing.JCheckBox tenue_de_compte;
    private javax.swing.JTextField tenue_de_compte_input;
    private javax.swing.JTextField thusand;
    private javax.swing.JTextField total_withdrawal_charges;
    private javax.swing.JComboBox<String> transaction_code;
    private com.toedter.calendar.JDateChooser transaction_date;
    private javax.swing.JTextField transaction_description;
    private javax.swing.JComboBox<String> transaction_type;
    private javax.swing.JTextField twenty;
    private javax.swing.JTextField twok;
    // End of variables declaration//GEN-END:variables
    private void saveBillatage(int transaction_id, String accountNumber){
        try {
            String sql = "INSERT INTO `billetage`(`id`,`transaction_id`, `account_number`, `5000`, `2000`, `1000`, `500`, `100`, `50`, `20`, `10`, `5`, `1`, `date_created`) "
                    + "VALUES (0,?,?,?,?,?,?,?,?,?,?,?,?,NOW())";
            pst = conn.connection.prepareStatement(sql);
            pst.setInt(1, transaction_id);
            pst.setString(2, accountNumber);
            pst.setInt(3, Integer.parseInt(fivek.getText()));
            pst.setInt(4, Integer.parseInt(twok.getText()));
            pst.setInt(5, Integer.parseInt(thusand.getText()));
            pst.setInt(6, Integer.parseInt(fivehundred.getText()));
            pst.setInt(7, Integer.parseInt(hundred.getText()));
            pst.setInt(8, Integer.parseInt(fifty.getText()));
            pst.setInt(9, Integer.parseInt(twenty.getText()));
            pst.setInt(10, Integer.parseInt(ten.getText()));
            pst.setInt(11, Integer.parseInt(five.getText()));
            pst.setInt(12, Integer.parseInt(one.getText()));
            pst.execute();
            System.out.println("Billetage is saved");
        } catch (SQLException ex) {
            Logger.getLogger(Deposit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
